export enum PortcallTimestampType {
  ETA_Berth = 'ETA-Berth',
  RTA_Berth = 'RTA-Berth',
  PTA_Berth = 'PTA-Berth',
  ETA_PBP = 'ETA-PBP',
  RTA_PBP = 'RTA-PBP',
  PTA_PBP = 'PTA-PBP',
  ATA_PBP = 'ATA-PBP',
  ATA_Berth = 'ATA-Berth',
  ATS_Cargo_Ops = 'ATS Cargo Ops',
  ETC_Cargo_Ops = 'ETC Cargo Ops',
  RTC_Cargo_Ops = 'RTC Cargo Ops',
  PTC_Cargo_Ops = 'PTC Cargo Ops',
  ATC_Cargo_Ops = 'ATC Cargo Ops',
  ETD_Berth = 'ETD-Berth',
  RTD_Berth = 'RTD-Berth',
  PTD_Berth = 'PTD-Berth',
  ATD_Berth = 'ATD-Berth',
  ATS_Pilot = "ATS Pilot"
}
