/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.records;


import java.time.LocalDateTime;

import org.dcsa.portcall.db.tables.CarrierVesselPortHistory;
import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarrierVesselPortHistoryRecord extends TableRecordImpl<CarrierVesselPortHistoryRecord> implements Record8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.carrier_vessel_port_history.id</code>.
     */
    public CarrierVesselPortHistoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.vessel</code>.
     */
    public CarrierVesselPortHistoryRecord setVessel(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.vessel</code>.
     */
    public Integer getVessel() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.port_of_call</code>.
     */
    public CarrierVesselPortHistoryRecord setPortOfCall(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.port_of_call</code>.
     */
    public Integer getPortOfCall() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.port_previous</code>.
     */
    public CarrierVesselPortHistoryRecord setPortPrevious(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.port_previous</code>.
     */
    public Integer getPortPrevious() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.port_next</code>.
     */
    public CarrierVesselPortHistoryRecord setPortNext(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.port_next</code>.
     */
    public Integer getPortNext() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.terminal</code>.
     */
    public CarrierVesselPortHistoryRecord setTerminal(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.terminal</code>.
     */
    public Integer getTerminal() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.carrier</code>.
     */
    public CarrierVesselPortHistoryRecord setCarrier(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.carrier</code>.
     */
    public Integer getCarrier() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.last_update</code>.
     */
    public CarrierVesselPortHistoryRecord setLastUpdate(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.ID;
    }

    @Override
    public Field<Integer> field2() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.VESSEL;
    }

    @Override
    public Field<Integer> field3() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.PORT_OF_CALL;
    }

    @Override
    public Field<Integer> field4() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.PORT_PREVIOUS;
    }

    @Override
    public Field<Integer> field5() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.PORT_NEXT;
    }

    @Override
    public Field<Integer> field6() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.TERMINAL;
    }

    @Override
    public Field<Integer> field7() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.CARRIER;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY.LAST_UPDATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getVessel();
    }

    @Override
    public Integer component3() {
        return getPortOfCall();
    }

    @Override
    public Integer component4() {
        return getPortPrevious();
    }

    @Override
    public Integer component5() {
        return getPortNext();
    }

    @Override
    public Integer component6() {
        return getTerminal();
    }

    @Override
    public Integer component7() {
        return getCarrier();
    }

    @Override
    public LocalDateTime component8() {
        return getLastUpdate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getVessel();
    }

    @Override
    public Integer value3() {
        return getPortOfCall();
    }

    @Override
    public Integer value4() {
        return getPortPrevious();
    }

    @Override
    public Integer value5() {
        return getPortNext();
    }

    @Override
    public Integer value6() {
        return getTerminal();
    }

    @Override
    public Integer value7() {
        return getCarrier();
    }

    @Override
    public LocalDateTime value8() {
        return getLastUpdate();
    }

    @Override
    public CarrierVesselPortHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord value2(Integer value) {
        setVessel(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord value3(Integer value) {
        setPortOfCall(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord value4(Integer value) {
        setPortPrevious(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord value5(Integer value) {
        setPortNext(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord value6(Integer value) {
        setTerminal(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord value7(Integer value) {
        setCarrier(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord value8(LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public CarrierVesselPortHistoryRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarrierVesselPortHistoryRecord
     */
    public CarrierVesselPortHistoryRecord() {
        super(CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY);
    }

    /**
     * Create a detached, initialised CarrierVesselPortHistoryRecord
     */
    public CarrierVesselPortHistoryRecord(Integer id, Integer vessel, Integer portOfCall, Integer portPrevious, Integer portNext, Integer terminal, Integer carrier, LocalDateTime lastUpdate) {
        super(CarrierVesselPortHistory.CARRIER_VESSEL_PORT_HISTORY);

        setId(id);
        setVessel(vessel);
        setPortOfCall(portOfCall);
        setPortPrevious(portPrevious);
        setPortNext(portNext);
        setTerminal(terminal);
        setCarrier(carrier);
        setLastUpdate(lastUpdate);
    }
}
