/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.records;


import java.time.LocalDate;

import org.dcsa.portcall.db.tables.LinerCode;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinerCodeRecord extends UpdatableRecordImpl<LinerCodeRecord> implements Record5<Integer, String, String, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.liner_code.id</code>.
     */
    public LinerCodeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.liner_code.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.liner_code.smdg_code</code>.
     */
    public LinerCodeRecord setSmdgCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.liner_code.smdg_code</code>.
     */
    public String getSmdgCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.liner_code.line</code>.
     */
    public LinerCodeRecord setLine(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.liner_code.line</code>.
     */
    public String getLine() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.liner_code.valid_from</code>.
     */
    public LinerCodeRecord setValidFrom(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.liner_code.valid_from</code>.
     */
    public LocalDate getValidFrom() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.liner_code.website</code>.
     */
    public LinerCodeRecord setWebsite(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.liner_code.website</code>.
     */
    public String getWebsite() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDate, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, LocalDate, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return LinerCode.LINER_CODE.ID;
    }

    @Override
    public Field<String> field2() {
        return LinerCode.LINER_CODE.SMDG_CODE;
    }

    @Override
    public Field<String> field3() {
        return LinerCode.LINER_CODE.LINE;
    }

    @Override
    public Field<LocalDate> field4() {
        return LinerCode.LINER_CODE.VALID_FROM;
    }

    @Override
    public Field<String> field5() {
        return LinerCode.LINER_CODE.WEBSITE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSmdgCode();
    }

    @Override
    public String component3() {
        return getLine();
    }

    @Override
    public LocalDate component4() {
        return getValidFrom();
    }

    @Override
    public String component5() {
        return getWebsite();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSmdgCode();
    }

    @Override
    public String value3() {
        return getLine();
    }

    @Override
    public LocalDate value4() {
        return getValidFrom();
    }

    @Override
    public String value5() {
        return getWebsite();
    }

    @Override
    public LinerCodeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LinerCodeRecord value2(String value) {
        setSmdgCode(value);
        return this;
    }

    @Override
    public LinerCodeRecord value3(String value) {
        setLine(value);
        return this;
    }

    @Override
    public LinerCodeRecord value4(LocalDate value) {
        setValidFrom(value);
        return this;
    }

    @Override
    public LinerCodeRecord value5(String value) {
        setWebsite(value);
        return this;
    }

    @Override
    public LinerCodeRecord values(Integer value1, String value2, String value3, LocalDate value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinerCodeRecord
     */
    public LinerCodeRecord() {
        super(LinerCode.LINER_CODE);
    }

    /**
     * Create a detached, initialised LinerCodeRecord
     */
    public LinerCodeRecord(Integer id, String smdgCode, String line, LocalDate validFrom, String website) {
        super(LinerCode.LINER_CODE);

        setId(id);
        setSmdgCode(smdgCode);
        setLine(line);
        setValidFrom(validFrom);
        setWebsite(website);
    }
}
