/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.records;


import org.dcsa.portcall.db.enums.EventClassifier;
import org.dcsa.portcall.db.enums.LocationType;
import org.dcsa.portcall.db.enums.PortCallTimestampType;
import org.dcsa.portcall.db.enums.TransportEventType;
import org.dcsa.portcall.db.tables.PortcallTimestampMapping;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortcallTimestampMappingRecord extends TableRecordImpl<PortcallTimestampMappingRecord> implements Record5<Integer, PortCallTimestampType, LocationType, EventClassifier, TransportEventType> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.portcall_timestamp_mapping.id</code>.
     */
    public PortcallTimestampMappingRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.timestamp_type</code>.
     */
    public PortcallTimestampMappingRecord setTimestampType(PortCallTimestampType value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.timestamp_type</code>.
     */
    public PortCallTimestampType getTimestampType() {
        return (PortCallTimestampType) get(1);
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.location</code>.
     */
    public PortcallTimestampMappingRecord setLocation(LocationType value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.location</code>.
     */
    public LocationType getLocation() {
        return (LocationType) get(2);
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.event_classiefier</code>.
     */
    public PortcallTimestampMappingRecord setEventClassiefier(EventClassifier value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.event_classiefier</code>.
     */
    public EventClassifier getEventClassiefier() {
        return (EventClassifier) get(3);
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.transport_event</code>.
     */
    public PortcallTimestampMappingRecord setTransportEvent(TransportEventType value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.transport_event</code>.
     */
    public TransportEventType getTransportEvent() {
        return (TransportEventType) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, PortCallTimestampType, LocationType, EventClassifier, TransportEventType> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, PortCallTimestampType, LocationType, EventClassifier, TransportEventType> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PortcallTimestampMapping.PORTCALL_TIMESTAMP_MAPPING.ID;
    }

    @Override
    public Field<PortCallTimestampType> field2() {
        return PortcallTimestampMapping.PORTCALL_TIMESTAMP_MAPPING.TIMESTAMP_TYPE;
    }

    @Override
    public Field<LocationType> field3() {
        return PortcallTimestampMapping.PORTCALL_TIMESTAMP_MAPPING.LOCATION;
    }

    @Override
    public Field<EventClassifier> field4() {
        return PortcallTimestampMapping.PORTCALL_TIMESTAMP_MAPPING.EVENT_CLASSIEFIER;
    }

    @Override
    public Field<TransportEventType> field5() {
        return PortcallTimestampMapping.PORTCALL_TIMESTAMP_MAPPING.TRANSPORT_EVENT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public PortCallTimestampType component2() {
        return getTimestampType();
    }

    @Override
    public LocationType component3() {
        return getLocation();
    }

    @Override
    public EventClassifier component4() {
        return getEventClassiefier();
    }

    @Override
    public TransportEventType component5() {
        return getTransportEvent();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public PortCallTimestampType value2() {
        return getTimestampType();
    }

    @Override
    public LocationType value3() {
        return getLocation();
    }

    @Override
    public EventClassifier value4() {
        return getEventClassiefier();
    }

    @Override
    public TransportEventType value5() {
        return getTransportEvent();
    }

    @Override
    public PortcallTimestampMappingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PortcallTimestampMappingRecord value2(PortCallTimestampType value) {
        setTimestampType(value);
        return this;
    }

    @Override
    public PortcallTimestampMappingRecord value3(LocationType value) {
        setLocation(value);
        return this;
    }

    @Override
    public PortcallTimestampMappingRecord value4(EventClassifier value) {
        setEventClassiefier(value);
        return this;
    }

    @Override
    public PortcallTimestampMappingRecord value5(TransportEventType value) {
        setTransportEvent(value);
        return this;
    }

    @Override
    public PortcallTimestampMappingRecord values(Integer value1, PortCallTimestampType value2, LocationType value3, EventClassifier value4, TransportEventType value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PortcallTimestampMappingRecord
     */
    public PortcallTimestampMappingRecord() {
        super(PortcallTimestampMapping.PORTCALL_TIMESTAMP_MAPPING);
    }

    /**
     * Create a detached, initialised PortcallTimestampMappingRecord
     */
    public PortcallTimestampMappingRecord(Integer id, PortCallTimestampType timestampType, LocationType location, EventClassifier eventClassiefier, TransportEventType transportEvent) {
        super(PortcallTimestampMapping.PORTCALL_TIMESTAMP_MAPPING);

        setId(id);
        setTimestampType(timestampType);
        setLocation(location);
        setEventClassiefier(eventClassiefier);
        setTransportEvent(transportEvent);
    }
}
