/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.records;


import org.dcsa.portcall.db.tables.Terminal;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TerminalRecord extends UpdatableRecordImpl<TerminalRecord> implements Record5<Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.terminal.id</code>.
     */
    public TerminalRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.terminal.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.terminal.port</code>.
     */
    public TerminalRecord setPort(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.terminal.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.terminal.smdg_code</code>.
     */
    public TerminalRecord setSmdgCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.terminal.smdg_code</code>.
     */
    public String getSmdgCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.terminal.terminal_name</code>.
     */
    public TerminalRecord setTerminalName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.terminal.terminal_name</code>.
     */
    public String getTerminalName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.terminal.terminal_operator</code>.
     */
    public TerminalRecord setTerminalOperator(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.terminal.terminal_operator</code>.
     */
    public String getTerminalOperator() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Terminal.TERMINAL.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Terminal.TERMINAL.PORT;
    }

    @Override
    public Field<String> field3() {
        return Terminal.TERMINAL.SMDG_CODE;
    }

    @Override
    public Field<String> field4() {
        return Terminal.TERMINAL.TERMINAL_NAME;
    }

    @Override
    public Field<String> field5() {
        return Terminal.TERMINAL.TERMINAL_OPERATOR;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPort();
    }

    @Override
    public String component3() {
        return getSmdgCode();
    }

    @Override
    public String component4() {
        return getTerminalName();
    }

    @Override
    public String component5() {
        return getTerminalOperator();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPort();
    }

    @Override
    public String value3() {
        return getSmdgCode();
    }

    @Override
    public String value4() {
        return getTerminalName();
    }

    @Override
    public String value5() {
        return getTerminalOperator();
    }

    @Override
    public TerminalRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TerminalRecord value2(Integer value) {
        setPort(value);
        return this;
    }

    @Override
    public TerminalRecord value3(String value) {
        setSmdgCode(value);
        return this;
    }

    @Override
    public TerminalRecord value4(String value) {
        setTerminalName(value);
        return this;
    }

    @Override
    public TerminalRecord value5(String value) {
        setTerminalOperator(value);
        return this;
    }

    @Override
    public TerminalRecord values(Integer value1, Integer value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TerminalRecord
     */
    public TerminalRecord() {
        super(Terminal.TERMINAL);
    }

    /**
     * Create a detached, initialised TerminalRecord
     */
    public TerminalRecord(Integer id, Integer port, String smdgCode, String terminalName, String terminalOperator) {
        super(Terminal.TERMINAL);

        setId(id);
        setPort(port);
        setSmdgCode(smdgCode);
        setTerminalName(terminalName);
        setTerminalOperator(terminalOperator);
    }
}
