INSERT INTO delay_code (smdg_code, "name", delay_type, description)
VALUES ('ACC', 'Accident involving personnel', 'SHIP Related', 'Accident involving personnel, vessel Related  ')
     , ('DEV', 'Deviation to avoid bad weather', 'SHIP Related', 'Deviation to avoid bad weather  ')
     , ('EDD', 'Emergency Dry Docking', 'SHIP Related', 'Emergency Dry Docking  ')
     , ('ENG', 'Engine repairs', 'SHIP Related', 'Engine repairs  ')
     , ('MVX', 'Proforma moves exceeded', 'SHIP Related', 'Proforma moves exceeded  ')
     , ('PAU', 'Vessel detained by port authorities', 'SHIP Related', 'Vessel detained by port authorities  ')
     , ('SPE', 'Ship - personnel or equipment unavailable', 'SHIP Related',
        'Ship - personnel or equipment not ready or unavailable  ')
     , ('STW', 'Stowage adjustment', 'SHIP Related', 'Stowage adjustment  ')
     , ('VGR', 'Vessel Gear Breakdown', 'SHIP Related', 'Vessel Gear Breakdown  ')
     , ('OTV', 'Others - Vessel Related', 'SHIP Related', 'Others - Vessel Related  ')
;
INSERT INTO delay_code (smdg_code, "name", delay_type, description)
VALUES ('AIP', 'Accident involving personnel', 'SHORE Related', 'Terminal accident involving personnel  ')
     , ('ANA', 'Authorities not available', 'SHORE Related', 'Authorities not available  ')
     , ('BUN', 'Bunkering delays', 'SHORE Related', 'Bunkering delays  ')
     , ('CGS', 'Arr OFF Proforma - Berth congestion', 'SHORE Related', 'Arr OFF Proforma - Berth congestion  ')
     , ('CRN', 'Crane shortage', 'SHORE Related', 'Crane shortage  ')
     , ('FTE', 'Failure or unavailability of Terminal equipment', 'SHORE Related',
        'Failure or unavailability of Terminal equipment  ')
     , ('HLD', 'Hatch Lids', 'SHORE Related', 'Hatch Lids  ')
     , ('LAB', 'Labor Shortage', 'SHORE Related', 'Labor Shortage  ')
     , ('LAS', 'Lashing delays', 'SHORE Related', 'Lashing delays  ')
     , ('LOT', 'Labour - Other', 'SHORE Related', 'Labour - Other  ')
;
INSERT INTO delay_code (smdg_code, "name", delay_type, description)
VALUES ('MIL', 'Military excercise', 'SHORE Related', 'Military excercise  ')
     , ('PBC', 'Arr ON Proforma - Berth congestion', 'SHORE Related', 'Arr ON Proforma - Berth congestion  ')
     , ('PIT', 'Pilot / Tug not available', 'SHORE Related', 'Pilot / Tug not available  ')
     , ('PLT', 'Planning (Terminal)', 'SHORE Related', 'Planning at Terminal  ')
     , ('PRD', 'Low Productivity', 'SHORE Related', 'Low Productivity  ')
     , ('QUA', 'Quarantine Inspection', 'SHORE Related', 'Quarantine Inspection by Authorities')
     , ('YRD', 'Yard congestion', 'SHORE Related', 'Yard congestion  ')
     , ('OTS', 'Others - Shore Related', 'SHORE Related', 'Others - Shore Related  ')
     , ('CAE', 'Cargo - Awaiting Exports', 'CARGO Related', 'Cargo - Awaiting Exports  ')
     , ('CIN', 'Cargo inspection by Authorities', 'CARGO Related', 'Cargo inspection by Authorities  ')
;
INSERT INTO delay_code (smdg_code, "name", delay_type, description)
VALUES ('DIN', 'Deficient or inadequate information', 'CARGO Related', 'Deficient or inadequate information   ')
     , ('LEK', 'Leaking Container', 'CARGO Related', 'Leaking Container  ')
     , ('REF', 'Reefer malfunction', 'CARGO Related', 'Reefer malfunction  ')
     , ('SPH', 'Special cargo handling', 'CARGO Related', 'Special cargo handling including Dangerous Goods (DG) ')
     , ('STF', 'Misstuffed Container', 'CARGO Related', 'Misstuffed Container  ')
     , ('UCC', 'Non-containerised cargo handling', 'CARGO Related',
        'Non-containerised (break bulk) or OOG (out of gauge) cargo handling requiring manual intervention   ')
     , ('WGT', 'Misdeclared Cargo weight', 'CARGO Related', 'Misdeclared Cargo weight  ')
     , ('OTC', 'Others - Cargo Related', 'CARGO Related', 'Others - Cargo Related  ')
     , ('HOL', 'Bank Holidays', 'Force Majeure', 'Bank Holidays  ')
     , ('QUV', 'Quarantine Vessel', 'Force Majeure', 'Quarantine Vessel before berthing due to epidemic')
;
INSERT INTO delay_code (smdg_code, "name", delay_type, description)
VALUES ('PTF', 'Port traffic restrictions', 'Force Majeure', 'Port traffic restrictions  ')
     , ('RSC', 'Save and Rescue', 'Force Majeure', 'Save and Rescue  ')
     , ('STR', 'Strike', 'Force Majeure', 'Strike  ')
     , ('TID', 'Tidal restrictions', 'Force Majeure', 'Tidal restrictions  ')
     , ('VIN', 'Vessel inspections by Coast Guard ', 'Force Majeure', 'Vessel inspections by Coast Guard   ')
     , ('WEA', 'Bad weather', 'Force Majeure', 'Bad weather  ')
     , ('OTF', 'Others - Force Majeure Related', 'Force Majeure', 'Others - Force Majeure Related  ')
     , ('OMIT', 'Port Omission', 'Planned Events',
        'Omission of a port call that was contained in the original schedule')
     , ('PHIN', 'Phase-in       ', 'Planned Events', 'The vessel joins a Service in this port.')
     , ('PHOT', 'Phase-out      ', 'Planned Events', 'The vessel leaves a Service in this port.')
;
INSERT INTO delay_code (smdg_code, "name", delay_type, description)
VALUES ('DRYD', 'Drydock        ', 'Planned Events', 'Planned dry docking')
     , ('ADHO', 'Adhoc call     ', 'Planned Events',
        'A port call is added which was not in the proforma for load+discharge operations')
     , ('ROTC', 'Rotation change', 'Planned Events', 'The sequence of port calls is changed compared to the proforma.')
     , ('BUNK', 'Bunker call    ', 'Planned Events',
        'A port call is added which was not in the proforma, only for bunkering, not for load+discharge operations')
     , ('OOSV', 'Layby          ', 'Planned Events', 'Out of Service')
;