INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Abu Dhabi', 'AE', 'AEAUH', 'AUH')
     , ('Jebel Ali', 'AE', 'AEJEA', 'JEA')
     , ('Mina Khalifa/Abu Dhabi', 'AE', 'AEKHL', 'KHL')
     , ('Khor al Fakkan', 'AE', 'AEKLF', 'KLF')
     , ('Sharjah', 'AE', 'AESHJ', 'SHJ')
     , ('Luanda', 'AO', 'AOLAD', 'LAD')
     , ('Bahia Blanca', 'AR', 'ARBHI', 'BHI')
     , ('Buenos Aires', 'AR', 'ARBUE', 'BUE')
     , ('Las Palmas', 'AR', 'ARLPS', 'LPS')
     , ('Mar del Plata', 'AR', 'ARMDQ', 'MDQ')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Puerto Madryn', 'AR', 'ARPMY', 'PMY')
     , ('Puerto Deseado', 'AR', 'ARPUD', 'PUD')
     , ('Rosario', 'AR', 'ARROS', 'ROS')
     , ('San Antonio Este', 'AR', 'ARSAE', 'SAE')
     , ('Ushuaia', 'AR', 'ARUSH', 'USH')
     , ('Zarate', 'AR', 'ARZAE', 'ZAE')
     , ('Pago Pago', 'AS', 'ASPPG', 'PPG')
     , ('Adelaide', 'AU', 'AUADL', 'ADL')
     , ('Bell Bay', 'AU', 'AUBEL', 'BEL')
     , ('Brisbane', 'AU', 'AUBNE', 'BNE')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Burnie', 'AU', 'AUBWT', 'BWT')
     , ('Darwin', 'AU', 'AUDRW', 'DRW')
     , ('Fremantle', 'AU', 'AUFRE', 'FRE')
     , ('Geelong', 'AU', 'AUGEX', 'GEX')
     , ('Gladstone', 'AU', 'AUGLT', 'GLT')
     , ('Hamilton', 'AU', 'AUHLT', 'HLT')
     , ('Melbourne', 'AU', 'AUMEL', 'MEL')
     , ('Port Kembla', 'AU', 'AUPKL', 'PKL')
     , ('Sydney', 'AU', 'AUSYD', 'SYD')
     , ('Oranjestad', 'AW', 'AWORJ', 'ORJ')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Chattogram', 'BD', 'BDCGP', 'CGP')
     , ('Munshiganj', 'BD', 'BDMUN', 'MUN')
     , ('Antwerpen', 'BE', 'BEANR', 'ANR')
     , ('Zeebrugge', 'BE', 'BEZEE', 'ZEE')
     , ('Bahrain International Airport', 'BH', 'BHBAH', 'BAH')
     , ('Cotonou', 'BJ', 'BJCOO', 'COO')
     , ('Fortaleza', 'BR', 'BRFOR', 'FOR')
     , ('Imbituba', 'BR', 'BRIBB', 'IBB')
     , ('Itapoa', 'BR', 'BRIOA', 'IOA')
     , ('Itajai', 'BR', 'BRITJ', 'ITJ')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Manaus', 'BR', 'BRMAO', 'MAO')
     , ('Navegantes', 'BR', 'BRNVT', 'NVT')
     , ('Pecem Pt/Sao Goncalo do Amarante', 'BR', 'BRPEC', 'PEC')
     , ('Paranagua', 'BR', 'BRPNG', 'PNG')
     , ('Rio Grande', 'BR', 'BRRIG', 'RIG')
     , ('Rio de Janeiro', 'BR', 'BRRIO', 'RIO')
     , ('Sao Francisco do Sul', 'BR', 'BRSFS', 'SFS')
     , ('Sao Luis', 'BR', 'BRSLZ', 'SLZ')
     , ('Itaguai Pt = Sepetiba Pt', 'BR', 'BRSPB', 'SPB')
     , ('Salvador', 'BR', 'BRSSA', 'SSA')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Santos', 'BR', 'BRSSZ', 'SSZ')
     , ('Suape', 'BR', 'BRSUA', 'SUA')
     , ('Vila do Conde Pt/Barcarena', 'BR', 'BRVDC', 'VDC')
     , ('Vitoria Pt', 'BR', 'BRVIX', 'VIX')
     , ('Halifax', 'CA', 'CAHAL', 'HAL')
     , ('Montreal', 'CA', 'CAMTR', 'MTR')
     , ('Prince Rupert', 'CA', 'CAPRR', 'PRR')
     , ('Vancouver', 'CA', 'CAVAN', 'VAN')
     , ('Pointe Noire', 'CG', 'CGPNR', 'PNR')
     , ('Abidjan', 'CI', 'CIABJ', 'ABJ')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Antofagasta', 'CL', 'CLANF', 'ANF')
     , ('Arica', 'CL', 'CLARI', 'ARI')
     , ('Coronel', 'CL', 'CLCNL', 'CNL')
     , ('Iquique', 'CL', 'CLIQQ', 'IQQ')
     , ('Lirquen', 'CL', 'CLLQN', 'LQN')
     , ('Puerto Angamos', 'CL', 'CLPAG', 'PAG')
     , ('Punta Arenas', 'CL', 'CLPUQ', 'PUQ')
     , ('San Antonio', 'CL', 'CLSAI', 'SAI')
     , ('San Vicente', 'CL', 'CLSVE', 'SVE')
     , ('Valparaiso', 'CL', 'CLVAP', 'VAP')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Chongqing', 'CN', 'CNCQI', 'CQI')
     , ('Chiwan Pt', 'CN', 'CNCWN', 'CWN')
     , ('Dalian', 'CN', 'CNDAL', 'DAL')
     , ('DA CHAN BAY', 'CN', 'CNDCB', 'DCB')
     , ('Fuzhou', 'CN', 'CNFZH', 'FZH')
     , ('Lianyungang', 'CN', 'CNLYG', 'LYG')
     , ('Ningbo', 'CN', 'CNNBO', 'NBO')
     , ('Nanjing', 'CN', 'CNNJI', 'NJI')
     , ('Nansha Pt', 'CN', 'CNNSA', 'NSA')
     , ('Qingdao', 'CN', 'CNQIN', 'QIN')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Rizhao Pt', 'CN', 'CNRZH', 'RZH')
     , ('Shanghai', 'CN', 'CNSGH', 'SGH')
     , ('Shekou Pt', 'CN', 'CNSHK', 'SHK')
     , ('Shantou Pt', 'CN', 'CNSTG', 'STG')
     , ('Taicang Pt', 'CN', 'CNTAC', 'TAC')
     , ('Tianjin', 'CN', 'CNTNJ', 'TNJ')
     , ('Weihai', 'CN', 'CNWEI', 'WEI')
     , ('Xiamen', 'CN', 'CNXAM', 'XAM')
     , ('Yantai', 'CN', 'CNYAT', 'YAT')
     , ('Yingkou Pt', 'CN', 'CNYIK', 'YIK')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Yantian Pt', 'CN', 'CNYTN', 'YTN')
     , ('Barranquilla', 'CO', 'COBAQ', 'BAQ')
     , ('Buenaventura', 'CO', 'COBUN', 'BUN')
     , ('Cartagena', 'CO', 'COCTG', 'CTG')
     , ('Santa Marta', 'CO', 'COSMR', 'SMR')
     , ('Turbo', 'CO', 'COTRB', 'TRB')
     , ('Caldera', 'CR', 'CRCAL', 'CAL')
     , ('Puerto Limon', 'CR', 'CRLIO', 'LIO')
     , ('Moin', 'CR', 'CRMOB', 'MOB')
     , ('La Habana', 'CU', 'CUHAV', 'HAV')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Mariel', 'CU', 'CUMAR', 'MAR')
     , ('Willemstad', 'CW', 'CWWIL', 'WIL')
     , ('Limassol', 'CY', 'CYLMS', 'LMS')
     , ('Bremerhaven', 'DE', 'DEBRV', 'BRV')
     , ('Hamburg', 'DE', 'DEHAM', 'HAM')
     , ('Wilhelmshaven', 'DE', 'DEWVN', 'WVN')
     , ('Aalborg', 'DK', 'DKAAL', 'AAL')
     , ('Aarhus', 'DK', 'DKAAR', 'AAR')
     , ('Kobenhavn', 'DK', 'DKCPH', 'CPH')
     , ('Fredericia', 'DK', 'DKFRC', 'FRC')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Kalundborg', 'DK', 'DKKAL', 'KAL')
     , ('Caucedo', 'DO', 'DOCAU', 'CAU')
     , ('Rio Haina', 'DO', 'DOHAI', 'HAI')
     , ('San Pedro de Macoris', 'DO', 'DOSPM', 'SPM')
     , ('Alger (Algiers)', 'DZ', 'DZALG', 'ALG')
     , ('Oran', 'DZ', 'DZORN', 'ORN')
     , ('Guayaquil', 'EC', 'ECGYE', 'GYE')
     , ('Puerto Bolivar', 'EC', 'ECPBO', 'PBO')
     , ('Posorja', 'EC', 'ECPSJ', 'PSJ')
     , ('Muuga', 'EE', 'EEMUG', 'MUG')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('El Iskandariya (Alexandria)', 'EG', 'EGALY', 'ALY')
     , ('Dumyat (Damietta)', 'EG', 'EGDAM', 'DAM')
     , ('Port Said', 'EG', 'EGPSD', 'PSD')
     , ('Sokhna Port', 'EG', 'EGSOK', 'SOK')
     , ('Lanzarote', 'ES', 'ESACE', 'ACE')
     , ('Malaga', 'ES', 'ESAGP', 'AGP')
     , ('Algeciras', 'ES', 'ESALG', 'ALG')
     , ('Barcelona', 'ES', 'ESBCN', 'BCN')
     , ('Bilbao', 'ES', 'ESBIO', 'BIO')
     , ('Cadiz', 'ES', 'ESCAD', 'CAD')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Cartagena', 'ES', 'ESCAR', 'CAR')
     , ('Ceuta', 'ES', 'ESCEU', 'CEU')
     , ('Gijon', 'ES', 'ESGIJ', 'GIJ')
     , ('Huelva', 'ES', 'ESHUV', 'HUV')
     , ('La Coruna (A Coruna)', 'ES', 'ESLCG', 'LCG')
     , ('Las Palmas de Gran Canaria', 'ES', 'ESLPA', 'LPA')
     , ('Melilla', 'ES', 'ESMLN', 'MLN')
     , ('Marin, Pontevedra', 'ES', 'ESMPG', 'MPG')
     , ('Sagunto', 'ES', 'ESSAG', 'SAG')
     , ('Santa Cruz de Tenerife', 'ES', 'ESSCT', 'SCT')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Tarragona', 'ES', 'ESTAR', 'TAR')
     , ('Vigo', 'ES', 'ESVGO', 'VGO')
     , ('Valencia', 'ES', 'ESVLC', 'VLC')
     , ('Helsingfors (Helsinki)', 'FI', 'FIHEL', 'HEL')
     , ('Fredrikshamn (Hamina)', 'FI', 'FIHMN', 'HMN')
     , ('Karleby (Kokkola)', 'FI', 'FIKOK', 'KOK')
     , ('Kotka', 'FI', 'FIKTK', 'KTK')
     , ('Mantyluoto', 'FI', 'FIMTY', 'MTY')
     , ('Rauma (Raumo)', 'FI', 'FIRAU', 'RAU')
     , ('Turku (Abo)', 'FI', 'FITKU', 'TKU')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Suva', 'FJ', 'FJSUV', 'SUV')
     , ('Dunkerque', 'FR', 'FRDKK', 'DKK')
     , ('Fos-sur-Mer', 'FR', 'FRFOS', 'FOS')
     , ('Le Havre', 'FR', 'FRLEH', 'LEH')
     , ('Montoir-de-Bretagne', 'FR', 'FRMTX', 'MTX')
     , ('Owendo', 'GA', 'GAOWE', 'OWE')
     , ('Belfast', 'GB', 'GBBEL', 'BEL')
     , ('Felixstowe', 'GB', 'GBFXT', 'FXT')
     , ('Grangemouth', 'GB', 'GBGRG', 'GRG')
     , ('Greenock', 'GB', 'GBGRK', 'GRK')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Hull', 'GB', 'GBHUL', 'HUL')
     , ('London Gateway Port', 'GB', 'GBLGP', 'LGP')
     , ('Liverpool', 'GB', 'GBLIV', 'LIV')
     , ('Rochester', 'GB', 'GBRCS', 'RCS')
     , ('Southampton', 'GB', 'GBSOU', 'SOU')
     , ('Teesport', 'GB', 'GBTEE', 'TEE')
     , ('Tilbury', 'GB', 'GBTIL', 'TIL')
     , ('Poti', 'GE', 'GEPTI', 'PTI')
     , ('Tema', 'GH', 'GHTEM', 'TEM')
     , ('Takoradi', 'GH', 'GHTKD', 'TKD')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Gibraltar', 'GI', 'GIGIB', 'GIB')
     , ('Piraeus', 'GR', 'GRPIR', 'PIR')
     , ('Thessaloniki', 'GR', 'GRSKG', 'SKG')
     , ('Puerto Barrios', 'GT', 'GTPBR', 'PBR')
     , ('Puerto Quetzal', 'GT', 'GTPRQ', 'PRQ')
     , ('Puerto Santo Tomas de Castilla', 'GT', 'GTSTC', 'STC')
     , ('Hong Kong', 'HK', 'HKHKG', 'HKG')
     , ('Puerto Cortes', 'HN', 'HNPCR', 'PCR')
     , ('San Lorenzo', 'HN', 'HNSLO', 'SLO')
     , ('Rijeka', 'HR', 'HRRJK', 'RJK')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Port-au-Prince', 'HT', 'HTPAP', 'PAP')
     , ('Banjarmasin', 'ID', 'IDBDJ', 'BDJ')
     , ('Batam Island', 'ID', 'IDBTM', 'BTM')
     , ('Jakarta, Java', 'ID', 'IDJKT', 'JKT')
     , ('Palembang, Sumatra', 'ID', 'IDPLM', 'PLM')
     , ('Surabaya', 'ID', 'IDSUB', 'SUB')
     , ('Dublin', 'IE', 'IEDUB', 'DUB')
     , ('Cork', 'IE', 'IEORK', 'ORK')
     , ('Ashdod', 'IL', 'ILASH', 'ASH')
     , ('Haifa', 'IL', 'ILHFA', 'HFA')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Kolkata (ex Calcutta)', 'IN', 'INCCU', 'CCU')
     , ('Cochin', 'IN', 'INCOK', 'COK')
     , ('Ennore', 'IN', 'INENR', 'ENR')
     , ('Mangalore', 'IN', 'INIXE', 'IXE')
     , ('Chennai (ex Madras)', 'IN', 'INMAA', 'MAA')
     , ('Mundra', 'IN', 'INMUN', 'MUN')
     , ('Jawaharlal Nehru (Nhava Sheva)', 'IN', 'INNSA', 'NSA')
     , ('Port Pipavav', 'IN', 'INPPV', 'PPV')
     , ('Tuticorin', 'IN', 'INTUT', 'TUT')
     , ('Visakhapatnam', 'IN', 'INVTZ', 'VTZ')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Umm Qasr Port', 'IQ', 'IQUQR', 'UQR')
     , ('Reykjavik', 'IS', 'ISREY', 'REY')
     , ('Ancona', 'IT', 'ITAOI', 'AOI')
     , ('Cagliari', 'IT', 'ITCAG', 'CAG')
     , ('Catania', 'IT', 'ITCTA', 'CTA')
     , ('Civitavecchia', 'IT', 'ITCVV', 'CVV')
     , ('Gioia Tauro', 'IT', 'ITGIT', 'GIT')
     , ('Genova', 'IT', 'ITGOA', 'GOA')
     , ('Livorno', 'IT', 'ITLIV', 'LIV')
     , ('Napoli', 'IT', 'ITNAP', 'NAP')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Ravenna', 'IT', 'ITRAN', 'RAN')
     , ('Salerno', 'IT', 'ITSAL', 'SAL')
     , ('La Spezia', 'IT', 'ITSPE', 'SPE')
     , ('Trieste', 'IT', 'ITTRS', 'TRS')
     , ('Venezia', 'IT', 'ITVCE', 'VCE')
     , ('Vado Ligure', 'IT', 'ITVDL', 'VDL')
     , ('Kingston', 'JM', 'JMKIN', 'KIN')
     , ('Al Aqabah', 'JO', 'JOAQJ', 'AQJ')
     , ('Aburatsu', 'JP', 'JPABU', 'ABU')
     , ('Akita', 'JP', 'JPAXT', 'AXT')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Chiba', 'JP', 'JPCHB', 'CHB')
     , ('Fukuyama, Hiroshima', 'JP', 'JPFKY', 'FKY')
     , ('Hachinohe', 'JP', 'JPHHE', 'HHE')
     , ('Hitachinaka', 'JP', 'JPHIC', 'HIC')
     , ('Hiroshima', 'JP', 'JPHIJ', 'HIJ')
     , ('Himeji', 'JP', 'JPHIM', 'HIM')
     , ('Hakata/Fukuoka', 'JP', 'JPHKT', 'HKT')
     , ('Hamada', 'JP', 'JPHMD', 'HMD')
     , ('Hososhima', 'JP', 'JPHSM', 'HSM')
     , ('Hitachi', 'JP', 'JPHTC', 'HTC')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Imabari', 'JP', 'JPIMB', 'IMB')
     , ('Imari', 'JP', 'JPIMI', 'IMI')
     , ('Ishikari', 'JP', 'JPISI', 'ISI')
     , ('Iwakuni', 'JP', 'JPIWK', 'IWK')
     , ('Kochi', 'JP', 'JPKCZ', 'KCZ')
     , ('Niigata', 'JP', 'JPKIJ', 'KIJ')
     , ('Kamaishi', 'JP', 'JPKIS', 'KIS')
     , ('Kumamoto', 'JP', 'JPKMJ', 'KMJ')
     , ('Kanazawa', 'JP', 'JPKNZ', 'KNZ')
     , ('Komatsushima', 'JP', 'JPKOM', 'KOM')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Kashima, Ibaraki', 'JP', 'JPKSM', 'KSM')
     , ('Kawasaki', 'JP', 'JPKWS', 'KWS')
     , ('Maizuru', 'JP', 'JPMAI', 'MAI')
     , ('Mizushima', 'JP', 'JPMIZ', 'MIZ')
     , ('Mikawa', 'JP', 'JPMKW', 'MKW')
     , ('Mishima, Kawanoe', 'JP', 'JPMKX', 'MKX')
     , ('Moji/Kitakyushu', 'JP', 'JPMOJ', 'MOJ')
     , ('Muroran', 'JP', 'JPMUR', 'MUR')
     , ('Matsuyama', 'JP', 'JPMYJ', 'MYJ')
     , ('Naha, Okinawa', 'JP', 'JPNAH', 'NAH')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Nakanoseki', 'JP', 'JPNAN', 'NAN')
     , ('Naoetsu', 'JP', 'JPNAO', 'NAO')
     , ('Nagoya, Aichi', 'JP', 'JPNGO', 'NGO')
     , ('Nagasaki', 'JP', 'JPNGS', 'NGS')
     , ('Oita', 'JP', 'JPOIT', 'OIT')
     , ('Omaezaki', 'JP', 'JPOMZ', 'OMZ')
     , ('Onahama', 'JP', 'JPONA', 'ONA')
     , ('Osaka', 'JP', 'JPOSA', 'OSA')
     , ('Otake', 'JP', 'JPOTK', 'OTK')
     , ('Sakaisenboku', 'JP', 'JPSBK', 'SBK')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Shibushi', 'JP', 'JPSBS', 'SBS')
     , ('Sendaishiogama', 'JP', 'JPSGM', 'SGM')
     , ('Sakata', 'JP', 'JPSKT', 'SKT')
     , ('Sakaiminato', 'JP', 'JPSMN', 'SMN')
     , ('Shimotsu', 'JP', 'JPSMT', 'SMT')
     , ('Shimizu', 'JP', 'JPSMZ', 'SMZ')
     , ('Toyohashi', 'JP', 'JPTHS', 'THS')
     , ('Tokuyama', 'JP', 'JPTKY', 'TKY')
     , ('Tomakomai', 'JP', 'JPTMK', 'TMK')
     , ('Tsuruga', 'JP', 'JPTRG', 'TRG')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Tottori', 'JP', 'JPTTJ', 'TTJ')
     , ('Tokyo', 'JP', 'JPTYO', 'TYO')
     , ('Ube', 'JP', 'JPUBJ', 'UBJ')
     , ('Kobe', 'JP', 'JPUKB', 'UKB')
     , ('Wakkanai', 'JP', 'JPWKJ', 'WKJ')
     , ('Yokkaichi', 'JP', 'JPYKK', 'YKK')
     , ('Yokohama', 'JP', 'JPYOK', 'YOK')
     , ('Mombasa', 'KE', 'KEMBA', 'MBA')
     , ('Kampong Saom', 'KH', 'KHKOS', 'KOS')
     , ('Incheon', 'KR', 'KRINC', 'INC')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Gwangyang', 'KR', 'KRKAN', 'KAN')
     , ('Pohang', 'KR', 'KRKPO', 'KPO')
     , ('Pyeongtaek', 'KR', 'KRPTK', 'PTK')
     , ('Busan', 'KR', 'KRPUS', 'PUS')
     , ('Ulsan', 'KR', 'KRUSN', 'USN')
     , ('Shuaiba', 'KW', 'KWSAA', 'SAA')
     , ('Shuwaikh', 'KW', 'KWSWK', 'SWK')
     , ('Beirut', 'LB', 'LBBEY', 'BEY')
     , ('Colombo', 'LK', 'LKCMB', 'CMB')
     , ('Klaipeda', 'LT', 'LTKLJ', 'KLJ')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Riga', 'LV', 'LVRIX', 'RIX')
     , ('Casablanca', 'MA', 'MACAS', 'CAS')
     , ('Tanger Med', 'MA', 'MAPTM', 'PTM')
     , ('Tangier', 'MA', 'MATNG', 'TNG')
     , ('Yangon', 'MM', 'MMRGN', 'RGN')
     , ('Nouakchott', 'MR', 'MRNKC', 'NKC')
     , ('Marsaxlokk', 'MT', 'MTMAR', 'MAR')
     , ('Altamira', 'MX', 'MXATM', 'ATM')
     , ('Ensenada', 'MX', 'MXESE', 'ESE')
     , ('Lazaro Cardenas', 'MX', 'MXLZC', 'LZC')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Mazatlan', 'MX', 'MXMZT', 'MZT')
     , ('Progreso', 'MX', 'MXPGO', 'PGO')
     , ('Tapachula', 'MX', 'MXTAP', 'TAP')
     , ('Tuxpan', 'MX', 'MXTUX', 'TUX')
     , ('Veracruz', 'MX', 'MXVER', 'VER')
     , ('Manzanillo', 'MX', 'MXZLO', 'ZLO')
     , ('Penang (Georgetown)', 'MY', 'MYPEN', 'PEN')
     , ('Pasir Gudang, Johor', 'MY', 'MYPGU', 'PGU')
     , ('Port Klang (Pelabuhan Klang)', 'MY', 'MYPKG', 'PKG')
     , ('Tanjung Pelepas', 'MY', 'MYTPP', 'TPP')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Maputo', 'MZ', 'MZMPM', 'MPM')
     , ('Walvis Bay', 'NA', 'NAWVB', 'WVB')
     , ('Apapa', 'NG', 'NGAPP', 'APP')
     , ('Port Harcourt', 'NG', 'NGPHC', 'PHC')
     , ('Tincan/Lagos', 'NG', 'NGTIN', 'TIN')
     , ('Corinto', 'NI', 'NICIO', 'CIO')
     , ('Amsterdam', 'NL', 'NLAMS', 'AMS')
     , ('Rotterdam', 'NL', 'NLRTM', 'RTM')
     , ('Vlissingen', 'NL', 'NLVLI', 'VLI')
     , ('Alesund', 'NO', 'NOAES', 'AES')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Bergen', 'NO', 'NOBGO', 'BGO')
     , ('Fredrikstad', 'NO', 'NOFRK', 'FRK')
     , ('Halden', 'NO', 'NOHAL', 'HAL')
     , ('Larvik', 'NO', 'NOLAR', 'LAR')
     , ('Moss', 'NO', 'NOMSS', 'MSS')
     , ('Oslo', 'NO', 'NOOSL', 'OSL')
     , ('Skjerkoya', 'NO', 'NOSKI', 'SKI')
     , ('Tananger', 'NO', 'NOTAE', 'TAE')
     , ('Auckland', 'NZ', 'NZAKL', 'AKL')
     , ('Lyttelton', 'NZ', 'NZLYT', 'LYT')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Napier', 'NZ', 'NZNPE', 'NPE')
     , ('New Plymouth', 'NZ', 'NZNPL', 'NPL')
     , ('Nelson', 'NZ', 'NZNSN', 'NSN')
     , ('Port Chalmers', 'NZ', 'NZPOE', 'POE')
     , ('Timaru', 'NZ', 'NZTIU', 'TIU')
     , ('Tauranga', 'NZ', 'NZTRG', 'TRG')
     , ('Wellington', 'NZ', 'NZWLG', 'WLG')
     , ('Salalah', 'OM', 'OMSLL', 'SLL')
     , ('Sohar', 'OM', 'OMSOH', 'SOH')
     , ('Balboa', 'PA', 'PABLB', 'BLB')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Cristobal', 'PA', 'PACTB', 'CTB')
     , ('Manzanillo', 'PA', 'PAMIT', 'MIT')
     , ('Colon', 'PA', 'PAONX', 'ONX')
     , ('Rodman', 'PA', 'PAROD', 'ROD')
     , ('Callao', 'PE', 'PECLL', 'CLL')
     , ('Paita', 'PE', 'PEPAI', 'PAI')
     , ('Papeete', 'PF', 'PFPPT', 'PPT')
     , ('Cebu', 'PH', 'PHCEB', 'CEB')
     , ('Manila', 'PH', 'PHMNL', 'MNL')
     , ('Muhammad Bin Qasim/Karachi', 'PK', 'PKBQM', 'BQM')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Karachi', 'PK', 'PKKHI', 'KHI')
     , ('Gdansk', 'PL', 'PLGDN', 'GDN')
     , ('Gdynia', 'PL', 'PLGDY', 'GDY')
     , ('Szczecin', 'PL', 'PLSZZ', 'SZZ')
     , ('San Juan', 'PR', 'PRSJU', 'SJU')
     , ('Canical', 'PT', 'PTCNL', 'CNL')
     , ('Figueira da Foz', 'PT', 'PTFDF', 'FDF')
     , ('Funchal, Madeira', 'PT', 'PTFNC', 'FNC')
     , ('Leixoes', 'PT', 'PTLEI', 'LEI')
     , ('Lisboa', 'PT', 'PTLIS', 'LIS')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Porto Santo Island', 'PT', 'PTPXO', 'PXO')
     , ('Setubal', 'PT', 'PTSET', 'SET')
     , ('Sines', 'PT', 'PTSIE', 'SIE')
     , ('Asuncion', 'PY', 'PYASU', 'ASU')
     , ('Pilar', 'PY', 'PYPIL', 'PIL')
     , ('San Antonio', 'PY', 'PYSAN', 'SAN')
     , ('Villeta', 'PY', 'PYVLL', 'VLL')
     , ('Doha', 'QA', 'QADOH', 'DOH')
     , ('BGN/PCGN1956 - HAMAD', 'QA', 'QAHMD', 'HMD')
     , ('Le Port', 'RE', 'RELPT', 'LPT')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Constanta', 'RO', 'ROCND', 'CND')
     , ('Saint Petersburg (ex Leningrad)', 'RU', 'RULED', 'LED')
     , ('Novorossiysk', 'RU', 'RUNVS', 'NVS')
     , ('Ust-Luga', 'RU', 'RUULU', 'ULU')
     , ('Vladivostok', 'RU', 'RUVVO', 'VVO')
     , ('Vostochnyy Port', 'RU', 'RUVYP', 'VYP')
     , ('Ad Dammam', 'SA', 'SADMM', 'DMM')
     , ('Jeddah', 'SA', 'SAJED', 'JED')
     , ('Jubail', 'SA', 'SAJUB', 'JUB')
     , ('King Abdullah City', 'SA', 'SAKAC', 'KAC')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Port Sudan', 'SD', 'SDPZU', 'PZU')
     , ('Ahus', 'SE', 'SEAHU', 'AHU')
     , ('Goteborg', 'SE', 'SEGOT', 'GOT')
     , ('Gavle', 'SE', 'SEGVX', 'GVX')
     , ('Halmstad', 'SE', 'SEHAD', 'HAD')
     , ('Helsingborg', 'SE', 'SEHEL', 'HEL')
     , ('Kapellskar', 'SE', 'SEKPS', 'KPS')
     , ('Malmo', 'SE', 'SEMMA', 'MMA')
     , ('Norrkoping', 'SE', 'SENRK', 'NRK')
     , ('Nynashamn', 'SE', 'SENYN', 'NYN')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Stockholm', 'SE', 'SESTO', 'STO')
     , ('Vasteras', 'SE', 'SEVST', 'VST')
     , ('Singapore', 'SG', 'SGSIN', 'SIN')
     , ('Koper', 'SI', 'SIKOP', 'KOP')
     , ('Dakar', 'SN', 'SNDKR', 'DKR')
     , ('Paramaribo', 'SR', 'SRPBM', 'PBM')
     , ('Acajutla', 'SV', 'SVAQJ', 'AQJ')
     , ('La Union', 'SV', 'SVLUN', 'LUN')
     , ('Latakia', 'SY', 'SYLTK', 'LTK')
     , ('Tartus', 'SY', 'SYTTS', 'TTS')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Bangkok', 'TH', 'THBKK', 'BKK')
     , ('Laem Chabang', 'TH', 'THLCH', 'LCH')
     , ('Sahathai Coastal Seaport', 'TH', 'THSCS', 'SCS')
     , ('Tunis', 'TN', 'TNTUN', 'TUN')
     , ('Aliaga', 'TR', 'TRALI', 'ALI')
     , ('Gebze', 'TR', 'TRGEB', 'GEB')
     , ('Gemlik', 'TR', 'TRGEM', 'GEM')
     , ('Iskenderun', 'TR', 'TRISK', 'ISK')
     , ('Istanbul', 'TR', 'TRIST', 'IST')
     , ('Ä°zmir', 'TR', 'TRIZM', 'IZM')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Izmit', 'TR', 'TRIZT', 'IZT')
     , ('Port of Karasu', 'TR', 'TRKSP', 'KSP')
     , ('Mersin', 'TR', 'TRMER', 'MER')
     , ('Yarimca', 'TR', 'TRYAR', 'YAR')
     , ('Port-of-Spain', 'TT', 'TTPOS', 'POS')
     , ('Point Lisas', 'TT', 'TTPTS', 'PTS')
     , ('Keelung (Chilung)', 'TW', 'TWKEL', 'KEL')
     , ('Kaohsiung', 'TW', 'TWKHH', 'KHH')
     , ('Dar es Salaam', 'TZ', 'TZDAR', 'DAR')
     , ('Odesa', 'UA', 'UAODS', 'ODS')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Pivdennyi', 'UA', 'UAYUZ', 'YUZ')
     , ('Baltimore', 'US', 'USBAL', 'BAL')
     , ('Charleston', 'US', 'USCHS', 'CHS')
     , ('Honolulu', 'US', 'USHNL', 'HNL')
     , ('Houston', 'US', 'USHOU', 'HOU')
     , ('Wilmington', 'US', 'USILM', 'ILM')
     , ('Jacksonville', 'US', 'USJAX', 'JAX')
     , ('Los Angeles', 'US', 'USLAX', 'LAX')
     , ('Long Beach', 'US', 'USLGB', 'LGB')
     , ('Miami', 'US', 'USMIA', 'MIA')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Mobile', 'US', 'USMOB', 'MOB')
     , ('New Orleans', 'US', 'USMSY', 'MSY')
     , ('Port Hueneme', 'US', 'USNTD', 'NTD')
     , ('New York', 'US', 'USNYC', 'NYC')
     , ('Oakland', 'US', 'USOAK', 'OAK')
     , ('Norfolk', 'US', 'USORF', 'ORF')
     , ('Portland', 'US', 'USPDX', 'PDX')
     , ('Port Everglades', 'US', 'USPEF', 'PEF')
     , ('Philadelphia', 'US', 'USPHL', 'PHL')
     , ('Portsmouth', 'US', 'USPTM', 'PTM')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Savannah', 'US', 'USSAV', 'SAV')
     , ('Seattle', 'US', 'USSEA', 'SEA')
     , ('Tacoma', 'US', 'USTIW', 'TIW')
     , ('Montevideo', 'UY', 'UYMVD', 'MVD')
     , ('Punta Pereyra', 'UY', 'UYPTP', 'PTP')
     , ('Guanta', 'VE', 'VEGUT', 'GUT')
     , ('La Guaira', 'VE', 'VELAG', 'LAG')
     , ('Puerto Cabello', 'VE', 'VEPBL', 'PBL')
     , ('Haiphong', 'VN', 'VNHPH', 'HPH')
     , ('Ninh Hoa', 'VN', 'VNNIH', 'NIH')
;
INSERT INTO ports ("name", un_country, un_locode, un_location)
VALUES ('Ho Chi Minh City', 'VN', 'VNSGN', 'SGN')
     , ('Vung Tau', 'VN', 'VNVUT', 'VUT')
     , ('Apia', 'WS', 'WSAPW', 'APW')
     , ('Cape Town', 'ZA', 'ZACPT', 'CPT')
     , ('Durban', 'ZA', 'ZADUR', 'DUR')
     , ('Port of Ngqura', 'ZA', 'ZANGQ', 'NGQ')
     , ('Port Elizabeth', 'ZA', 'ZAPLZ', 'PLZ')
;