INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('AAL', 'Austral Asia Line', '2003-09-01', 'http://aalshipping.com')
     , ('ABC', 'ABC Containerline ', '2003-09-01', '')
     , ('ACL', 'Atlantic Container Line', '2003-09-01', 'http://www.aclcargo.com/')
     , ('ACS', 'ATLANTICARGO SERVICE ', '2003-09-01', 'https://atlanticcargo.ru')
     , ('ADM', 'Admiral Container Lines Inc. Ltd.', '2017-05-09', 'http://www.acolines.com')
     , ('ADV', 'Advance Container Lines', '2003-09-01', 'http://www.aclship.com')
     , ('AFL', 'American Feeder Lines, Boston', '2003-09-01', '')
     , ('AGX', 'Agrexco', '2003-09-01', 'http://www.agrexco.com')
     , ('AIC', 'African Independent Coastal Services', '2003-09-01', '')
     , ('AIL', 'Australasian Interocean Line  ', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('ALI', 'Alianca Navegacao Ltd., Brasil', '2003-09-01', 'http://www.alianca.com.br')
     , ('AMI', 'Amir Lines', '2003-09-01', '')
     , ('AMT', 'American Transport Line', '2003-09-01', '')
     , ('AND', 'Andes Operador Multimodal', '2015-12-08', '')
     , ('ANL', 'Australian National Line', '2003-09-01', 'https://www.anl.com.au/')
     , ('AOL', 'Apollo Line', '2003-09-01', 'http://www.apolloshipping.de')
     , ('APL', 'American President Line', '2003-09-01', 'http://www.apl.com/')
     , ('ARC', 'ARC Line (Sunmarine Shipping Services)', '2016-10-28', 'http://www.sunmarine.com')
     , ('ARK', 'Arkas Shipping', '2003-09-01', 'http://www.arkasline.com.tr')
     , ('ARP', 'ARPEZ', '2015-12-08', 'http://www.arpez.com.ar')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('ASC', 'Australia-Straits Container Line (ASCL)', '2003-09-01', '')
     , ('AWS', 'Andrew Weir Shipping', '2003-09-01', 'http://awshipmanagement.com/')
     , ('BAC', 'Bacoliner', '2003-09-01', '')
     , ('BAS', 'Baltic Sea Line', '2003-09-01', '')
     , ('BBL', 'Barber Wilhelmsen', '2003-09-01', 'https://www.wilhelmsen.com')
     , ('BCL', 'Baltic Container Line', '2003-09-01', 'http://balticline.fi/')
     , ('BCN', 'Bermuda Container Line', '2016-05-18', 'http://neptunebermuda.com/')
     , ('BDS', 'Bien Dong Shipping Co, Ha Noi City', '2003-09-01', 'http://www.biendong.com.vn/index.php?lang=en')
     , ('BEN', 'Ben Line Containers', '2003-09-01', 'http://www.benlineagencies.com/')
     , ('BGF', 'Bg Freight Line', '2003-09-01', 'http://bgfreightline.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('BLP', 'BLPL Singapore ', '2016-12-20', 'http://tgsblpl.com/')
     , ('BMC', 'BMC Line Shipping Egypt', '2003-09-01', 'http://www.bmclines.com/')
     , ('BMS', 'Bintang Mas Shipping ', '2003-09-01', 'http://www.bintangmas.com.sg/')
     , ('BOL', 'Bolt Orient Line Ltd.', '2003-09-01', '')
     , ('BON', 'Bonyad Marine Services', '2003-09-01', 'http://www.bosaco.ir/')
     , ('BOR', 'Borchard', '2003-09-01', 'http://www.borlines.com/')
     , ('BOS', 'Baltic Orient Shipping', '2003-09-01', 'http://balticoriental.com')
     , ('BRO', 'Brointermed Lines', '2015-02-18', 'http://www.brointermedlines.com/')
     , ('BSA', 'BSA Transportation ', '2003-09-01', '')
     , ('BSC', 'Bangladesh Shipping Corporation', '2003-09-01', 'http://bsc.portal.gov.bd/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('BSF', 'Bayswater Shipping and Forwarding ', '2003-09-01', 'http://www.bayswater.com.sg/')
     , ('BSK', 'B.S.K. Stevedoring ', '2003-09-01', '')
     , ('BSL', 'Blue Star Line', '2003-09-01', '')
     , ('BSW', 'Batamindo Shipping & Warehousing', '2003-09-01', 'http://www.bsw.com.sg/')
     , ('BTL', 'Bengal Tiger Line Singapore', '2003-09-01', 'http://www.btl-feeders.com/')
     , ('BUL', 'Bulcon', '2003-09-01', '')
     , ('CAM', 'Cameroun Shipping Lines', '2003-09-01', '')
     , ('CAP', 'Captrans Shipping', '2003-09-01', '')
     , ('CAU', 'CSAV Austral', '2015-07-13', 'www.csav.com/en/')
     , ('CAV', 'Compania Sud Americana De Vapores', '2003-09-01', 'http://www.csav.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('CCN', 'Co Chilena De Naveg. Interoceania S. A.', '2003-09-01', '')
     , ('CCS', 'Chief Container Services', '2003-09-01', '')
     , ('CFS', 'Caribbean Feeder Service Ltd., Kingston', '2003-09-01', 'http://crosseast-ae.com/index.html')
     , ('CES', 'Crosseast Shipping ', '2003-09-01', 'http://www.cscl.lk/')
     , ('CEY', 'Ceylon Shipping Corporation', '2003-09-01', 'https://www.caribbeanfeeder.com/')
     , ('CHL', 'Consortium Hispania Lines SA', '2003-09-01', 'http://www.chl.es/')
     , ('CLA', 'Clansa', '2003-09-01', '')
     , ('CLH', 'Clarion Shipping', '2016-05-04', 'http://www.clarionshipping.com')
     , ('CLN', 'Cheng Lie Navigation Co., Ltd.', '2003-09-01', 'http://www.cnc-line.com/')
     , ('CMA', 'CMA-CGM', '2003-09-01', 'http://www.cma-cgm.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('CMB', 'Company Maritim Belgique', '2003-09-01', 'https://www.cmb.be/')
     , ('CMC', 'Crowley Maritime Corp., Jacksonville, Fl.', '2003-09-01', 'http://www.crowley.com/')
     , ('CMN', 'COMANAV', '2003-09-01', 'www.camellia-line.co.jp/')
     , ('CML', 'Camellia Line', '2015-04-15', '')
     , ('CNA', 'Compagnie Nationale Algérienne de Navigation S.p.a ', '2003-09-01', 'http://www.cnan-nord.com/')
     , ('CNC', 'DONGSUE Shipping Co.Ltd.', '2003-09-01', 'http://www.dongsue.com/')
     , ('CNP', 'Consorcio Naviero Peruano', '2003-09-01', 'http://www.cnpsa.com/')
     , ('COE', 'COSCO SHIPPING Lines (Europe) GmbH ', '2015-04-08', 'http://en.coscocs.com/')
     , ('COO', 'Cool Carriers  ', '2003-09-01', 'http://www.cool.se/')
     , ('COR', 'Coreck Maritime', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('COS', 'COSCO SHIPPING Lines Co. Ltd ', '2003-09-01', 'http://en.coscocs.com/')
     , ('CRL', 'Croatia Line', '2003-09-01', '')
     , ('CSE', 'COSCO South East Asia Pte. Ltd.', '2003-09-01', 'http://en.coscocs.com/')
     , ('CSF', 'Cathay Shipping & Freight Services', '2003-09-01', 'http://www.cathayshpg.com/')
     , ('CSH', 'Containerships Ltd Oy Helsinki', '2003-09-01', 'http://www.containershipsgroup.com/')
     , ('CSI', 'Cosiarma, Costa Rica', '2003-09-01', 'http://www.cosiarmacr.com/')
     , ('CSL', 'Canada States Africa Line, Montreal', '2003-09-01', 'http://www.csaline.com/')
     , ('CWJ', 'PT Cumawis Jakarta  ', '2003-09-01', 'http://samudera.co.id/id/company/pt-cumawis')
     , ('DAF', 'Dafra Lines', '2003-09-01', '')
     , ('DAL', 'Deutsche Afrika Line', '2003-09-01', 'http://www.dal.biz/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('DBD', 'DB Deniz Nakiyata A.S.', '2003-09-01', 'http://www.tcl.com.tr/eng/index.asp')
     , ('DEL', 'Delmas', '2003-09-01', 'http://www.cma-cgm.com/the-group/markets/africa')
     , ('DEP', 'Deppe-Line', '2003-09-01', '')
     , ('DJL', 'PT Jakarta Lloyd', '2003-09-01', 'https://djakartalloyd.co.id/kantor-cabang/')
     , ('DJS', 'Dongjin Shipping Co, Pusan, Korea', '2003-09-01',
        'http://www.djship.com/en/fleet/dong-jin-shipping-2?ckattempt=1')
     , ('DLT', 'Delta Shipping Line', '2003-09-01', 'http://deltaship.com.tr/')
     , ('DNA', 'C&LINE Co.Ltd', '2003-09-01', '')
     , ('DPS', 'Delphis', '2003-09-01', 'https://www.cmb.be/en/division/delphis')
     , ('DSL', 'Dongnama Shipping ', '2003-09-01', '')
     , ('DSR', 'DSR/Senator', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('DUE', 'DONGBO Logistics Co.Ltd.,', '2003-09-01', 'http://www.dblkr.com/english/Company01.asp')
     , ('EAS', 'DONGSHIN OVERSEAS TRANSPORT', '2003-09-01', '')
     , ('ECL', 'Euro Container Lines', '2016-08-12', 'www.wilsonship.no/en/euro-container-line')
     , ('EGH', 'Evergreen Marine Hong Kong', '2003-09-01', 'https://www.evergreen-marine.com/')
     , ('EGY', 'Egyptian Navigation Co.', '2003-09-01', '')
     , ('EIM', 'Eimskip', '2003-09-01', 'http://www.eimskip.com/')
     , ('ELL', 'Ellerman', '2003-09-01', '')
     , ('ELM', 'Empressa Lineas Maritimas Argentinas', '2003-09-01', '')
     , ('ELS', 'Eng Lee Shipping', '2003-09-01', 'http://www.englee.com.sg/')
     , ('EMC', 'Evergreen Marine Corporation', '2017-05-10', 'https://www.evergreen-marine.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('EME', 'EMES Feedering, Monaco', '2016-08-12', 'www.emes-feedering.com')
     , ('EMS', 'Evergreen Marine (Singapore) Pte Ltd', '2003-09-01', 'https://www.evergreen-marine.com/')
     , ('EPC', 'EP Carriers ', '2003-09-01', 'http://www.epshipping.com.sg/')
     , ('ESL', 'Emirates Shipping Agencies Korea', '2003-09-01', 'http://www.emiratesline.com/')
     , ('EUC', 'Eucon', '2015-05-06', 'https://www.eucon.nl/')
     , ('FBS', 'Franco-Belgian Services ', '2003-09-01', 'www.maerskline.com/')
     , ('FCS', 'Fred-Olsen  Canary Services (FOCS)', '2003-09-01', 'https://www.fredolsen.es/en')
     , ('FED', 'Fednav', '2003-09-01', 'http://www.fednav.com/en')
     , ('FES', 'FESCO Lines Vladivostok Ltd', '2003-09-01', 'http://www.fesco.ru/en/')
     , ('FIN', 'Finnlines', '2003-09-01', 'https://www.finnlines.com/freight')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('FSA', 'Far Shipping Agencies Pte Ltd', '2016-05-02', 'http://www.farshipping.com/')
     , ('FSS', 'Foong Sun Shipping ', '2003-09-01', '')
     , ('GEFL', 'Gulf Express Freight Line ', '2003-09-01', 'http://www.gelogistic.com/')
     , ('GEK', 'Geniki Lines Singapore', '2003-09-01', 'http://www.geniki.com.my/')
     , ('GEM', 'Golden Eagle Maritime', '2003-09-01', '')
     , ('GMD', 'Gemadept Singapore', '2003-09-01', 'http://www.gemadept.com.vn/home.html')
     , ('GMS', 'Gemartrans ', '2003-09-01', 'http://com.niceshipping.com/GEMARTRANS/eindex.htm')
     , ('GNC', 'Grimaldi Lines', '2003-09-01', 'http://www.grimaldi.napoli.it/en/index.html')
     , ('GRF', 'Green Feeder', '2003-09-01', '')
     , ('GSL', 'Globe Star Shipping', '2003-09-01', 'http://www.globestar.co.in/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('GWF', 'Great White Fleet / Chiquita Bananas', '2003-09-01', 'https://www.greatwhitefleet.com/')
     , ('HKS', 'OY Hacklin Seatrans Ltd.', '2018-02-27', 'www.hacklin.fi')
     , ('HDS', 'Hafiz Darya Shipping Co', '2003-09-01', 'http://www.hdasco.com/')
     , ('HEA', 'Heung-A Shipping ', '2003-09-01', 'http://www.heung-a.com/')
     , ('HIL', 'Head International Logistics Co., LTD.', '2003-09-01', '')
     , ('HLC', 'Hapag Lloyd ', '2003-09-01', 'http://www.hapag-lloyd.com/')
     , ('HLM', 'Hai Leck Marine Containers', '2003-09-01', '')
     , ('HML', 'Hub Line', '2003-09-01', 'http://www.hubline.com/')
     , ('HMM', 'Hyundai', '2003-09-01', 'https://www.hmm21.com/cms/company/engn/index.jsp')
     , ('HMS', 'Holland Maas Shipping', '2003-09-01', 'http://www.weclines.com/index.php/about-us.html')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('HRC', 'HRC Shipping Limited, Dhaka', '2003-09-01', 'http://www.hrcbd.com/')
     , ('HSA', 'Hamburg Sud Americana', '2003-09-01', 'https://www.hamburgsud.com/')
     , ('HSD', 'Hamburg-Sud', '2003-09-01', 'https://www.hamburgsud.com/')
     , ('HST', 'Hugo Stinnes Line (Rostock)', '2015-05-16', 'http://www.stinnes-linien.de/')
     , ('HTM', 'Evergreen Marine (UK) Ltd. (Hatsu Marine) ', '2003-09-01', 'https://www.evergreen-marine.com/')
     , ('HYS', 'Hay Yang Shipping Co.', '2003-09-01', '')
     , ('IAL', 'Interasia Lines', '2003-09-01', 'http://www.interasia.cc/')
     , ('IBM', 'PT. Interbenua Medanperkasa', '2003-09-01', '')
     , ('IDL', 'Indrati Lines ', '2003-09-01', '')
     , ('IML', 'Intermarine ', '2003-09-01', 'http://intermarine.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('IRI', 'IRISL KOREA Co.Ltd', '2003-09-01', 'http://www.irisl.net/52/Home.aspx')
     , ('ISC', 'ISCONT', '2016-01-27', '')
     , ('ISL', 'Islamic Republic of Iran Shipping Lines', '2003-09-01', 'http://www.irisl.net/52/Home.aspx')
     , ('ITS', 'Italia Maritima SPA', '2003-09-01', 'http://www.italiamarittima.it/')
     , ('JBS', 'Jaya Baru Shipping ', '2003-09-01', '')
     , ('JOC', 'Josindo Container ', '2003-09-01', '')
     , ('JTK', 'P.T. Jasatama Kemasindo', '2003-09-01', '')
     , ('KEA', 'KEA Marine ', '2003-09-01', '')
     , ('KHS', 'Kien Hung Shipping ', '2003-09-01', '')
     , ('KJC', 'KUK JAE TRANSPORTATION CO.', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('KLI', 'K-Line (Kawasaki Kisen Kaisha)', '2003-09-01', 'https://www.kline.co.jp/en/')
     , ('KLK', 'Kawasaki Kinkai Kisen Kaisha', '2003-09-01', 'http://www.kawakin.co.jp/en/')
     , ('KLS', 'Keppel Logistics', '2003-09-01', 'http://www.keppellog.com/en/')
     , ('KMA', 'Coastal Shipping ', '2016-12-20', 'http://www.coastalshippingltd.com/')
     , ('KMT', 'Korea Marine Transport ', '2003-09-01', 'http://www.ekmtc.com/')
     , ('KOA', 'Koala Lines', '2003-09-01', '')
     , ('KOS', 'King Ocean Services', '2015-10-27', 'www.kingocean.com')
     , ('KSC', 'Korea Shipping Corp. ', '2003-09-01', 'http://www.smksc.co.kr/eng/')
     , ('KWS', 'Kyowa Shipping Co., Tokyo', '2003-09-01', 'https://www.kyowa-line.co.jp/en/')
     , ('LBA', 'Companhia Libra de Navegacao, Rio de Jan', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('LLB', 'Lloyd Brasileiro ', '2003-09-01', '')
     , ('MAC', 'MACS Maritime Carrier Shipping GmbH & C', '2003-09-01', 'https://www.macship.com/')
     , ('MAR', 'Maruba Line ', '2003-09-01', 'http://www.maruba.com.ar/en/')
     , ('MAT', 'Matson Navigation', '2015-04-21', 'https://www.matson.com/')
     , ('MBF', 'MBf Carpenter Shipping Kuala Lumpur', '2003-09-01', 'http://www.carpentersshipping.com/default.htm')
     , ('MCC', 'MCC Transport ', '2003-09-01', 'https://www.mcc.com.sg/')
     , ('MCL', 'MCL Shipping Co', '2003-09-01', 'http://www.mcl.ae/')
     , ('MCM', 'Marfret Compagnie Maritime', '2003-09-01', 'http://www.marfret.fr/en/')
     , ('MCV', 'Macvan', '2003-09-01', '')
     , ('MED', 'MEDKON Lines, Turkey', '2017-09-21', 'http://www.medkonlines.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('MEL', 'Mariana Express Lines, Singapore', '2003-09-01', 'https://www.mellship.com/')
     , ('MES', 'Messina Line, Genoa', '2016-09-15', 'www.messinaline.it')
     , ('MET', 'Metz Container Line.', '2003-09-01', 'http://www.metzcontainerline.com/')
     , ('MFI', 'Med Feeder Italia', '2003-09-01', '')
     , ('MFS', 'Myanma Five Star Line', '2003-09-01', 'http://www.fasa.org.sg/library/SSA0404001/MFSL/mfsl/index.html')
     , ('MGS', 'Megastar Shipping ', '2003-09-01', 'http://www.megastar.com.sg/')
     , ('MIS', 'Malaysian International Shipping Company', '2003-09-01', 'http://www.misc.com.my/')
     , ('MLM', 'Mann Lines, UK', '2016-01-10', 'http://www.mannlines.ee/ro-ro.html')
     , ('MMC', 'Melfi Marine Corporation, Cuba', '2016-09-30', 'www.melfimarine.cu')
     , ('MMI', 'Manii Maritime Inc', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('MOL', 'Mitsui OSK Lines', '2003-09-01', 'http://cms.molpower.com/')
     , ('MON', 'Montemar', '2003-09-01', '')
     , ('MRS', 'Maruba Sca Clan S.A', '2003-09-01', 'http://www.maruba.com.ar/en/')
     , ('MSC', 'Mediterranean Shipping Company', '2003-09-01', 'https://www.msc.com/deu')
     , ('MSK', 'Maersk', '2003-09-01',
        'https://www.maerskline.com/?gclid=EAIaIQobChMIsprD44-l2QIVHuAZCh2lVg6jEAAYASAAEgL29fD_BwE&gclsrc=aw.ds')
     , ('MSS', 'Maldives Shipping Singapore ', '2003-09-01', '')
     , ('MUO', 'Maritime United Operator (Madrid)', '2015-07-23', 'www.mtlfeeder.com/en/')
     , ('MYS', 'Malaysia Shipping Corporation', '2003-09-01', 'www.mar-united.com')
     , ('MTU', 'Maritime Tunesian Lines', '2003-09-01', '')
     , ('NAV', 'Navio Shipping ', '2016-12-20', 'http://www.navio-shipping.com/contact.php')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('NCL', 'North Sea Container Line', '2015-08-04', 'https://www.ncl.no/')
     , ('NDS', 'Nile Dutch Africa Lines', '2017-07-31', 'www.niledutch.com')
     , ('NGP', 'New Guinea Pacific Line', '2003-09-01', 'http://www.swireshipping.com/')
     , ('NIS', 'Nisa Maritima, Valencia, Spain', '2003-09-01', 'http://nisamaritima.es/?lang=en')
     , ('NLS', 'Neptune Lines Shipping, Liberia', '2003-09-01', 'http://www.neptunelines.com/')
     , ('NOB', 'Nobleza', '2015-12-08', '')
     , ('NOL', 'Neptune Orient Lines', '2003-09-01', 'https://www.nol.com.sg/')
     , ('NOR', 'Norasia Container Lines ', '2003-09-01', 'http://www.csav.com/en/pages/home.aspx')
     , ('NPL', 'Neptune Pacific Line', '2003-09-01', 'https://www.neptunepacific.com/')
     , ('NPS', 'New Pacific Shipping', '2003-09-01', 'http://www.newpacificline.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('NSL', 'NAMSUNG Shipping Co.Ltd', '2003-09-01', 'http://www.namsung.co.kr/eng/main.do')
     , ('NSS', 'NSCSA The National Shipping Company of Saudi Arabia (Bahri)', '2003-09-01',
        'http://www.bahri.sa/Bahri.aspx?lang=en-US')
     , ('NYK', 'Nippon Yusen Kabushiki Kaisha (NYK)', '2003-09-01',
        'https://www.nykline.com/ecom/CUP_HOM_3000.do?redir=Y')
     , ('OAC', 'Ocean Africa Container Lines (Durban)', '2017-05-24', 'http://oceanafrica.co.za/')
     , ('OBS', 'Ocean Bridge Shipping', '2003-09-01', 'https://www.oceanbridge.co.nz/')
     , ('OEL', 'Orient Express Lines', '2003-09-01', 'http://tgsoel.com/')
     , ('OMC', 'Orix Maritime Corp  ', '2003-09-01', 'http://www.orix.co.jp/grp/en/')
     , ('ONE', 'Ocean Network Express Pte. Ltd.', '2018-01-01', 'www.one-line.com')
     , ('OOL', 'Orient Overseas Container Line', '2003-09-01', 'http://www.oocl.com/eng/Pages/default.aspx')
     , ('OPD', 'OPDR', '2003-09-01', 'http://www.opdr.com/en/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('OSS', 'Orient Shipping Services', '2003-09-01', 'http://www.ossfeeders.com/')
     , ('OTA', 'Otal Atlantique', '2003-09-01', '')
     , ('PAC', 'Pacifica Shipping', '2003-09-01', 'http://www.pacship.co.nz/')
     , ('PAN', 'Pancon Shipping Singapore', '2003-09-01', 'http://pancon.com.sg/')
     , ('PAR', 'Paranave, Paraguay, Asuncion', '2017-12-20', 'http://www.navemar.com.py/english/paranave.php  ')
     , ('PAS', 'Pasha Lines, Hawaii', '2016-01-20', 'https://www.pashahawaii.com/ ')
     , ('PCC', 'PACC Container Line ', '2003-09-01', 'http://www.pacc.com.sg/')
     , ('PCI', 'PORTLINE Containers International', '2016-12-20', 'http://www.pci-containers.com/en/home')
     , ('PDZ', 'Perkapalan Dai Zun ', '2003-09-01', '')
     , ('PET', 'Petrotank', '2015-12-08', 'http://petrotank.net/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('PFL', 'Pacific Forum Line', '2003-09-01', 'https://www.pacificforumline.com/')
     , ('PHL', 'PHL Containers Line ', '2003-09-01', 'https://www.anacostia.com/railroads/phl')
     , ('PIL', 'Pacific International Lines', '2003-09-01',
        'https://www.pilship.com/en-pil-pacific-international-lines/1.html')
     , ('PKS', 'Perkins Shipping', '2003-09-01', '')
     , ('PLL', 'PIL SOC Services', '2003-09-01', 'https://www.pilship.com/')
     , ('PLS', 'PNS Logistics', '2003-09-01', 'http://www.pnsshipping.com/')
     , ('PND', 'PT Pelayaran Nusantara Delimadju', '2003-09-01', '')
     , ('PNS', 'Pakistan National Shipping Co.', '2003-09-01', 'https://www.pnsc.com.pk/')
     , ('POR', 'Portlink', '2003-09-01', 'http://www.mghgroup.com/portlink.html')
     , ('PSL', 'Pekanbaru Shipping', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('PTL', 'Petrolog Naigai ', '2003-09-01', '')
     , ('QAL', 'Queensland Asia Line  ', '2003-09-01', '')
     , ('QCL', 'QC Container Line ', '2003-09-01', 'http://qcline.com/')
     , ('RCL', 'Regional Container Line  ', '2003-09-01', 'https://www.rclgroup.com/')
     , ('RIL', 'Rickmers-Linie', '2003-09-01', 'http://www.rickmers-line.com/')
     , ('RMA', 'Richfield Marine Agencies (S) PTE LTD', '2016-05-02', 'www.richfield.com.sg')
     , ('SAF', 'Safmarine', '2003-09-01', 'https://www.safmarine.com/')
     , ('SAI', 'Saigon Shipping Company', '2003-09-01', 'http://www.saigonship.com.vn/Home.aspx?lang=en')
     , ('SAM', 'Samskip', '2003-09-01', 'https://www.samskip.com/')
     , ('SCI', 'Shipping Corporation of India', '2003-09-01', 'http://www.shipindia.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('SCL', 'Safmarine Container Lines', '2003-09-01', 'https://www.safmarine.com/')
     , ('SCS', 'Sea Consortium ', '2003-09-01', 'https://www.x-pressfeeders.com/')
     , ('SDS', 'Sindo Damai ', '2003-09-01', 'http://www.sindodamai.com.sg/')
     , ('SEA', 'Sea Connect Klaipeda, Lithuania', '2003-09-01', 'http://www.seaconnect.lt/')
     , ('SEN', 'Senator Line', '2003-09-01', '')
     , ('SET', 'Setramar', '2003-09-01', 'http://grupposetramar.it/')
     , ('SFS', 'Steamers Feederships ', '2003-09-01', '')
     , ('SGL', 'Seago Line Copenhagen', '2003-09-01', 'https://www.seagoline.com/company')
     , ('SHL', 'Seahawk Shipping ', '2016-12-20', 'http://www.seahawk.com.ph/Services.html')
     , ('SIM', 'Simatech Shipping Dubai', '2003-09-01', 'http://www.simatech.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('SIT', 'SITC Container Lines Co., Ltd', '2016-07-01', 'www.sitc.com')
     , ('SJL', 'Sarjak Container Lines', '2003-09-01', 'http://www.sarjak.com/')
     , ('SKS', 'Soon Kiat Shipping ', '2003-09-01', 'http://www.soonkiatship.com.sg/')
     , ('SKT', 'Sembawang Kimtrans ', '2003-09-01', '')
     , ('SLC', 'SM Line Corporation, Seoul', '2017-05-10', 'http://www.smlines.com/main.html')
     , ('SLD', 'Sealand', '2015-10-29', 'https://www.sealand.com/')
     , ('SLM', 'Salamis Lines, Cyprus', '2017-01-17', 'www.salamisshipping.com')
     , ('SMM', 'Sinokor Merchant Marine', '2003-09-01', 'http://www.sinokor.co.kr/')
     , ('SNL', 'Sinotrans Container Lines Co Ltd', '2003-09-01', 'http://www.sinolines.com/col/col498/index.html')
     , ('SPS', 'South Pacific Shipping', '2003-09-01', 'http://www.spsltd.co.nz/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('SSC', 'SSC Shipping Agencies Pte Ltd', '2003-09-01', 'http://singaporeshipping.listedcompany.com/')
     , ('SSL', 'Samudera', '2003-09-01', 'http://www1.samudera.com/ssl/')
     , ('SSS', 'Seastrong Shipping Agencies', '2016-05-02', '')
     , ('SST', 'Sea-Shore Transportation ', '2003-09-01', 'http://sslpak.com/')
     , ('STA', 'Star Shipping', '2003-09-01', 'http://www.starship.com.sg/')
     , ('STE', 'Steinacher', '2003-09-01', 'https://boschmanssteinacher.be/en/')
     , ('STX', 'STX PAN OCEAN', '2003-09-01', 'http://www.panocean.com/')
     , ('SWA', 'Swan Shipping', '2003-09-01', 'http://www.swan-line.com/')
     , ('SWI', 'Swire Shipping', '2003-09-01', 'http://www.swireshipping.com/')
     , ('SYG', 'Shin Yang Shipping Malaysia', '2003-09-01', 'https://www.syshippingcorp.com.my/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('SYM', 'Shandong Yantai Marine Shipping', '2003-09-01', '')
     , ('TAR', 'Tarros, La Spezia', '2017-09-29', 'http://www.tarros.it/home-en/')
     , ('TJS', 'Tong Joo Shipping Pte Ltd', '2016-05-02', '')
     , ('TMG', 'Transport Maritima Grancolombiana', '2003-09-01', '')
     , ('TMI', 'Transportes Maritimos Insulares, Lisbon', '2003-09-01', 'https://transinsular.pt/')
     , ('TNC', 'Transmares, Chile', '2015-09-24', 'http://www.transmares.cl/index.html ')
     , ('TOL', 'Tasman Orient Line', '2003-09-01', '')
     , ('TRK', 'Turkon Line', '2016-12-06', 'http://turkon.com/en/')
     , ('TRW', 'Transworld Feeders FZCO, Dubai', '2017-08-11', 'http://www.transworld.com/feeders/index.html')
     , ('TSK', 'Tokyo Senpaku Kaisha  ', '2003-09-01', '')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('TSL', 'T. S. Lines ', '2003-09-01', 'http://www.tslines.com/EN/')
     , ('TTR', 'Tru-Trans Malaysia', '2003-09-01', '')
     , ('TYS', 'Tai Young Shipping', '2003-09-01', 'http://www.taiyoungship.co.kr/')
     , ('UAF', 'United Africa Feeder Line (Mauritius)', '2017-04-03', 'http://www.uaflshipping.com/')
     , ('UAS', 'United Arab Shipping', '2003-09-01', 'https://www.hapag-lloyd.com/')
     , ('UBF', 'Chiquita Commercial Cargo Containers', '2003-09-01', 'https://www.greatwhitefleet.com/')
     , ('UFE', 'Unifeeder Aarhus', '2003-09-01', 'http://www.unifeeder.com/')
     , ('UFS', 'United Feeder Services Limassol', '2003-09-01', 'http://www.utdfeeder.com/')
     , ('USL', 'United States Line', '2003-09-01', '')
     , ('VAS', 'Vasco Maritime Line Singapore', '2003-09-01', 'http://vascomaritime.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('VEN', 'Venavega Venezuela', '2003-09-01', 'http://venavega.com.ve/')
     , ('VML', 'VM LINER FELIXSTOWE', '2015-02-18', 'http://www.vmliner.com/')
     , ('WDS', 'Westford ', '2003-09-01', '')
     , ('WEC', 'WEC', '2003-09-01', 'http://www.weclines.com/')
     , ('WEL', 'Worldgate Express Lines ', '2003-09-01', 'http://www.worldgate.com.sg/')
     , ('WGL', 'Welgrow Line ', '2003-09-01', 'https://www.welgrowindia.com/')
     , ('WHL', 'Wan Hai Lines', '2003-09-01', 'http://www.wanhai.com/')
     , ('WLS', 'White Line Shipping, UAE', '2016-01-12', 'http://www.whiteline.ae')
     , ('WWL', 'Wallenius Wilhelmsen Lines AS', '2003-09-01', 'https://www.2wglobal.com/')
     , ('XPF', 'X-PRESS FEEDERS', '2018-10-11', 'http://www.x-pressfeeders.com/')
;
INSERT INTO liner_code (smdg_code, line, valid_from, website)
VALUES ('YGL', 'Yemen Gulf Line', '2003-09-01', 'http://www.y-g-l.com/')
     , ('YML', 'Yang Ming Line', '2003-09-01', 'http://www.yangming.com/')
     , ('YSC', 'Yanghai Shipping, Seoul', '2003-09-01', 'http://www.yscline.com/')
     , ('ZIM', 'Zim Israel Navigation Company', '2003-09-01', 'http://www.zim.com/')
;