/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db;


import java.util.Arrays;
import java.util.List;

import org.dcsa.portcall.db.tables.Port;
import org.dcsa.portcall.db.tables.PortCallTimestamp;
import org.dcsa.portcall.db.tables.Terminal;
import org.dcsa.portcall.db.tables.Vessel;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -376209431;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.port</code>.
     */
    public final Port PORT = Port.PORT;

    /**
     * The table <code>public.port_call_timestamp</code>.
     */
    public final PortCallTimestamp PORT_CALL_TIMESTAMP = PortCallTimestamp.PORT_CALL_TIMESTAMP;

    /**
     * The table <code>public.terminal</code>.
     */
    public final Terminal TERMINAL = Terminal.TERMINAL;

    /**
     * The table <code>public.vessel</code>.
     */
    public final Vessel VESSEL = Vessel.VESSEL;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.PORT_CALL_TIMESTAMP_ID_SEQ,
            Sequences.PORT_ID_SEQ,
            Sequences.TERMINAL_ID_SEQ,
            Sequences.VESSEL_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Port.PORT,
            PortCallTimestamp.PORT_CALL_TIMESTAMP,
            Terminal.TERMINAL,
            Vessel.VESSEL);
    }
}
