/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Carrier implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    smdgCode;
    private String    name;
    private LocalDate validFrom;
    private String    website;

    public Carrier() {}

    public Carrier(Carrier value) {
        this.id = value.id;
        this.smdgCode = value.smdgCode;
        this.name = value.name;
        this.validFrom = value.validFrom;
        this.website = value.website;
    }

    public Carrier(
        Integer   id,
        String    smdgCode,
        String    name,
        LocalDate validFrom,
        String    website
    ) {
        this.id = id;
        this.smdgCode = smdgCode;
        this.name = name;
        this.validFrom = validFrom;
        this.website = website;
    }

    /**
     * Getter for <code>public.carrier.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.carrier.id</code>.
     */
    public Carrier setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.carrier.smdg_code</code>.
     */
    public String getSmdgCode() {
        return this.smdgCode;
    }

    /**
     * Setter for <code>public.carrier.smdg_code</code>.
     */
    public Carrier setSmdgCode(String smdgCode) {
        this.smdgCode = smdgCode;
        return this;
    }

    /**
     * Getter for <code>public.carrier.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.carrier.name</code>.
     */
    public Carrier setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.carrier.valid_from</code>.
     */
    public LocalDate getValidFrom() {
        return this.validFrom;
    }

    /**
     * Setter for <code>public.carrier.valid_from</code>.
     */
    public Carrier setValidFrom(LocalDate validFrom) {
        this.validFrom = validFrom;
        return this;
    }

    /**
     * Getter for <code>public.carrier.website</code>.
     */
    public String getWebsite() {
        return this.website;
    }

    /**
     * Setter for <code>public.carrier.website</code>.
     */
    public Carrier setWebsite(String website) {
        this.website = website;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Carrier (");

        sb.append(id);
        sb.append(", ").append(smdgCode);
        sb.append(", ").append(name);
        sb.append(", ").append(validFrom);
        sb.append(", ").append(website);

        sb.append(")");
        return sb.toString();
    }
}
