/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarrierVesselPortHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       vessel;
    private Integer       portOfCall;
    private Integer       portPrevious;
    private Integer       portNext;
    private Integer       terminal;
    private Integer       carrier;
    private LocalDateTime lastUpdate;

    public CarrierVesselPortHistory() {}

    public CarrierVesselPortHistory(CarrierVesselPortHistory value) {
        this.id = value.id;
        this.vessel = value.vessel;
        this.portOfCall = value.portOfCall;
        this.portPrevious = value.portPrevious;
        this.portNext = value.portNext;
        this.terminal = value.terminal;
        this.carrier = value.carrier;
        this.lastUpdate = value.lastUpdate;
    }

    public CarrierVesselPortHistory(
        Integer       id,
        Integer       vessel,
        Integer       portOfCall,
        Integer       portPrevious,
        Integer       portNext,
        Integer       terminal,
        Integer       carrier,
        LocalDateTime lastUpdate
    ) {
        this.id = id;
        this.vessel = vessel;
        this.portOfCall = portOfCall;
        this.portPrevious = portPrevious;
        this.portNext = portNext;
        this.terminal = terminal;
        this.carrier = carrier;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.id</code>.
     */
    public CarrierVesselPortHistory setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.vessel</code>.
     */
    public Integer getVessel() {
        return this.vessel;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.vessel</code>.
     */
    public CarrierVesselPortHistory setVessel(Integer vessel) {
        this.vessel = vessel;
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.port_of_call</code>.
     */
    public Integer getPortOfCall() {
        return this.portOfCall;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.port_of_call</code>.
     */
    public CarrierVesselPortHistory setPortOfCall(Integer portOfCall) {
        this.portOfCall = portOfCall;
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.port_previous</code>.
     */
    public Integer getPortPrevious() {
        return this.portPrevious;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.port_previous</code>.
     */
    public CarrierVesselPortHistory setPortPrevious(Integer portPrevious) {
        this.portPrevious = portPrevious;
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.port_next</code>.
     */
    public Integer getPortNext() {
        return this.portNext;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.port_next</code>.
     */
    public CarrierVesselPortHistory setPortNext(Integer portNext) {
        this.portNext = portNext;
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.terminal</code>.
     */
    public Integer getTerminal() {
        return this.terminal;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.terminal</code>.
     */
    public CarrierVesselPortHistory setTerminal(Integer terminal) {
        this.terminal = terminal;
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.carrier</code>.
     */
    public Integer getCarrier() {
        return this.carrier;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.carrier</code>.
     */
    public CarrierVesselPortHistory setCarrier(Integer carrier) {
        this.carrier = carrier;
        return this;
    }

    /**
     * Getter for <code>public.carrier_vessel_port_history.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>public.carrier_vessel_port_history.last_update</code>.
     */
    public CarrierVesselPortHistory setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CarrierVesselPortHistory (");

        sb.append(id);
        sb.append(", ").append(vessel);
        sb.append(", ").append(portOfCall);
        sb.append(", ").append(portPrevious);
        sb.append(", ").append(portNext);
        sb.append(", ").append(terminal);
        sb.append(", ").append(carrier);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
