/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;

import org.dcsa.portcall.db.enums.MessageDirection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer          id;
    private MessageDirection direction;
    private Integer          timestampId;
    private String           filename;
    private byte[]           payload;
    private String           transferId;
    private String           status;
    private String           detail;

    public Message() {}

    public Message(Message value) {
        this.id = value.id;
        this.direction = value.direction;
        this.timestampId = value.timestampId;
        this.filename = value.filename;
        this.payload = value.payload;
        this.transferId = value.transferId;
        this.status = value.status;
        this.detail = value.detail;
    }

    public Message(
        Integer          id,
        MessageDirection direction,
        Integer          timestampId,
        String           filename,
        byte[]           payload,
        String           transferId,
        String           status,
        String           detail
    ) {
        this.id = id;
        this.direction = direction;
        this.timestampId = timestampId;
        this.filename = filename;
        this.payload = payload;
        this.transferId = transferId;
        this.status = status;
        this.detail = detail;
    }

    /**
     * Getter for <code>public.message.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.message.id</code>.
     */
    public Message setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.message.direction</code>.
     */
    public MessageDirection getDirection() {
        return this.direction;
    }

    /**
     * Setter for <code>public.message.direction</code>.
     */
    public Message setDirection(MessageDirection direction) {
        this.direction = direction;
        return this;
    }

    /**
     * Getter for <code>public.message.timestamp_id</code>.
     */
    public Integer getTimestampId() {
        return this.timestampId;
    }

    /**
     * Setter for <code>public.message.timestamp_id</code>.
     */
    public Message setTimestampId(Integer timestampId) {
        this.timestampId = timestampId;
        return this;
    }

    /**
     * Getter for <code>public.message.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>public.message.filename</code>.
     */
    public Message setFilename(String filename) {
        this.filename = filename;
        return this;
    }

    /**
     * Getter for <code>public.message.payload</code>.
     */
    public byte[] getPayload() {
        return this.payload;
    }

    /**
     * Setter for <code>public.message.payload</code>.
     */
    public Message setPayload(byte[] payload) {
        this.payload = payload;
        return this;
    }

    /**
     * Getter for <code>public.message.transfer_id</code>.
     */
    public String getTransferId() {
        return this.transferId;
    }

    /**
     * Setter for <code>public.message.transfer_id</code>.
     */
    public Message setTransferId(String transferId) {
        this.transferId = transferId;
        return this;
    }

    /**
     * Getter for <code>public.message.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.message.status</code>.
     */
    public Message setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.message.detail</code>.
     */
    public String getDetail() {
        return this.detail;
    }

    /**
     * Setter for <code>public.message.detail</code>.
     */
    public Message setDetail(String detail) {
        this.detail = detail;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(id);
        sb.append(", ").append(direction);
        sb.append(", ").append(timestampId);
        sb.append(", ").append(filename);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(transferId);
        sb.append(", ").append(status);
        sb.append(", ").append(detail);

        sb.append(")");
        return sb.toString();
    }
}
