/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Port implements Serializable {

    private static final long serialVersionUID = -574224167;

    private Integer id;
    private String  name;
    private String  unCountry;
    private String  unLocode;
    private String  unLocation;
    private String  timezone;

    public Port() {}

    public Port(Port value) {
        this.id = value.id;
        this.name = value.name;
        this.unCountry = value.unCountry;
        this.unLocode = value.unLocode;
        this.unLocation = value.unLocation;
        this.timezone = value.timezone;
    }

    public Port(
        Integer id,
        String  name,
        String  unCountry,
        String  unLocode,
        String  unLocation,
        String  timezone
    ) {
        this.id = id;
        this.name = name;
        this.unCountry = unCountry;
        this.unLocode = unLocode;
        this.unLocation = unLocation;
        this.timezone = timezone;
    }

    public Integer getId() {
        return this.id;
    }

    public Port setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Port setName(String name) {
        this.name = name;
        return this;
    }

    public String getUnCountry() {
        return this.unCountry;
    }

    public Port setUnCountry(String unCountry) {
        this.unCountry = unCountry;
        return this;
    }

    public String getUnLocode() {
        return this.unLocode;
    }

    public Port setUnLocode(String unLocode) {
        this.unLocode = unLocode;
        return this;
    }

    public String getUnLocation() {
        return this.unLocation;
    }

    public Port setUnLocation(String unLocation) {
        this.unLocation = unLocation;
        return this;
    }

    public String getTimezone() {
        return this.timezone;
    }

    public Port setTimezone(String timezone) {
        this.timezone = timezone;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Port (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(unCountry);
        sb.append(", ").append(unLocode);
        sb.append(", ").append(unLocation);
        sb.append(", ").append(timezone);

        sb.append(")");
        return sb.toString();
    }
}
