/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.dcsa.portcall.db.enums.Direction;
import org.dcsa.portcall.db.enums.PortCallTimestampType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortCallTimestamp implements Serializable {

    private static final long serialVersionUID = -126183802;

    private Integer               id;
    private Integer               vessel;
    private Integer               portApproach;
    private Integer               portFrom;
    private Integer               portNext;
    private PortCallTimestampType timestampType;
    private OffsetDateTime        eventTimestamp;
    private OffsetDateTime        logOfCall;
    private Direction             direction;
    private Integer               terminal;
    private String                locationId;
    private String                changeComment;
    private Boolean               deleted;

    public PortCallTimestamp() {}

    public PortCallTimestamp(PortCallTimestamp value) {
        this.id = value.id;
        this.vessel = value.vessel;
        this.portApproach = value.portApproach;
        this.portFrom = value.portFrom;
        this.portNext = value.portNext;
        this.timestampType = value.timestampType;
        this.eventTimestamp = value.eventTimestamp;
        this.logOfCall = value.logOfCall;
        this.direction = value.direction;
        this.terminal = value.terminal;
        this.locationId = value.locationId;
        this.changeComment = value.changeComment;
        this.deleted = value.deleted;
    }

    public PortCallTimestamp(
        Integer               id,
        Integer               vessel,
        Integer               portApproach,
        Integer               portFrom,
        Integer               portNext,
        PortCallTimestampType timestampType,
        OffsetDateTime        eventTimestamp,
        OffsetDateTime        logOfCall,
        Direction             direction,
        Integer               terminal,
        String                locationId,
        String                changeComment,
        Boolean               deleted
    ) {
        this.id = id;
        this.vessel = vessel;
        this.portApproach = portApproach;
        this.portFrom = portFrom;
        this.portNext = portNext;
        this.timestampType = timestampType;
        this.eventTimestamp = eventTimestamp;
        this.logOfCall = logOfCall;
        this.direction = direction;
        this.terminal = terminal;
        this.locationId = locationId;
        this.changeComment = changeComment;
        this.deleted = deleted;
    }

    public Integer getId() {
        return this.id;
    }

    public PortCallTimestamp setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getVessel() {
        return this.vessel;
    }

    public PortCallTimestamp setVessel(Integer vessel) {
        this.vessel = vessel;
        return this;
    }

    public Integer getPortApproach() {
        return this.portApproach;
    }

    public PortCallTimestamp setPortApproach(Integer portApproach) {
        this.portApproach = portApproach;
        return this;
    }

    public Integer getPortFrom() {
        return this.portFrom;
    }

    public PortCallTimestamp setPortFrom(Integer portFrom) {
        this.portFrom = portFrom;
        return this;
    }

    public Integer getPortNext() {
        return this.portNext;
    }

    public PortCallTimestamp setPortNext(Integer portNext) {
        this.portNext = portNext;
        return this;
    }

    public PortCallTimestampType getTimestampType() {
        return this.timestampType;
    }

    public PortCallTimestamp setTimestampType(PortCallTimestampType timestampType) {
        this.timestampType = timestampType;
        return this;
    }

    public OffsetDateTime getEventTimestamp() {
        return this.eventTimestamp;
    }

    public PortCallTimestamp setEventTimestamp(OffsetDateTime eventTimestamp) {
        this.eventTimestamp = eventTimestamp;
        return this;
    }

    public OffsetDateTime getLogOfCall() {
        return this.logOfCall;
    }

    public PortCallTimestamp setLogOfCall(OffsetDateTime logOfCall) {
        this.logOfCall = logOfCall;
        return this;
    }

    public Direction getDirection() {
        return this.direction;
    }

    public PortCallTimestamp setDirection(Direction direction) {
        this.direction = direction;
        return this;
    }

    public Integer getTerminal() {
        return this.terminal;
    }

    public PortCallTimestamp setTerminal(Integer terminal) {
        this.terminal = terminal;
        return this;
    }

    public String getLocationId() {
        return this.locationId;
    }

    public PortCallTimestamp setLocationId(String locationId) {
        this.locationId = locationId;
        return this;
    }

    public String getChangeComment() {
        return this.changeComment;
    }

    public PortCallTimestamp setChangeComment(String changeComment) {
        this.changeComment = changeComment;
        return this;
    }

    public Boolean getDeleted() {
        return this.deleted;
    }

    public PortCallTimestamp setDeleted(Boolean deleted) {
        this.deleted = deleted;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PortCallTimestamp (");

        sb.append(id);
        sb.append(", ").append(vessel);
        sb.append(", ").append(portApproach);
        sb.append(", ").append(portFrom);
        sb.append(", ").append(portNext);
        sb.append(", ").append(timestampType);
        sb.append(", ").append(eventTimestamp);
        sb.append(", ").append(logOfCall);
        sb.append(", ").append(direction);
        sb.append(", ").append(terminal);
        sb.append(", ").append(locationId);
        sb.append(", ").append(changeComment);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
