/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;

import org.dcsa.portcall.db.enums.EventClassifier;
import org.dcsa.portcall.db.enums.LocationType;
import org.dcsa.portcall.db.enums.PortCallTimestampType;
import org.dcsa.portcall.db.enums.TransportEventType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortcallTimestampMapping implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer               id;
    private PortCallTimestampType timestampType;
    private LocationType          location;
    private EventClassifier       eventClassiefier;
    private TransportEventType    transportEvent;

    public PortcallTimestampMapping() {}

    public PortcallTimestampMapping(PortcallTimestampMapping value) {
        this.id = value.id;
        this.timestampType = value.timestampType;
        this.location = value.location;
        this.eventClassiefier = value.eventClassiefier;
        this.transportEvent = value.transportEvent;
    }

    public PortcallTimestampMapping(
        Integer               id,
        PortCallTimestampType timestampType,
        LocationType          location,
        EventClassifier       eventClassiefier,
        TransportEventType    transportEvent
    ) {
        this.id = id;
        this.timestampType = timestampType;
        this.location = location;
        this.eventClassiefier = eventClassiefier;
        this.transportEvent = transportEvent;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.id</code>.
     */
    public PortcallTimestampMapping setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.timestamp_type</code>.
     */
    public PortCallTimestampType getTimestampType() {
        return this.timestampType;
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.timestamp_type</code>.
     */
    public PortcallTimestampMapping setTimestampType(PortCallTimestampType timestampType) {
        this.timestampType = timestampType;
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.location</code>.
     */
    public LocationType getLocation() {
        return this.location;
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.location</code>.
     */
    public PortcallTimestampMapping setLocation(LocationType location) {
        this.location = location;
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.event_classiefier</code>.
     */
    public EventClassifier getEventClassiefier() {
        return this.eventClassiefier;
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.event_classiefier</code>.
     */
    public PortcallTimestampMapping setEventClassiefier(EventClassifier eventClassiefier) {
        this.eventClassiefier = eventClassiefier;
        return this;
    }

    /**
     * Getter for <code>public.portcall_timestamp_mapping.transport_event</code>.
     */
    public TransportEventType getTransportEvent() {
        return this.transportEvent;
    }

    /**
     * Setter for <code>public.portcall_timestamp_mapping.transport_event</code>.
     */
    public PortcallTimestampMapping setTransportEvent(TransportEventType transportEvent) {
        this.transportEvent = transportEvent;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PortcallTimestampMapping (");

        sb.append(id);
        sb.append(", ").append(timestampType);
        sb.append(", ").append(location);
        sb.append(", ").append(eventClassiefier);
        sb.append(", ").append(transportEvent);

        sb.append(")");
        return sb.toString();
    }
}
