/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Terminal implements Serializable {

    private static final long serialVersionUID = 2011681700;

    private Integer id;
    private Integer port;
    private String  smdgCode;
    private String  terminalName;
    private String  terminalOperator;

    public Terminal() {}

    public Terminal(Terminal value) {
        this.id = value.id;
        this.port = value.port;
        this.smdgCode = value.smdgCode;
        this.terminalName = value.terminalName;
        this.terminalOperator = value.terminalOperator;
    }

    public Terminal(
        Integer id,
        Integer port,
        String  smdgCode,
        String  terminalName,
        String  terminalOperator
    ) {
        this.id = id;
        this.port = port;
        this.smdgCode = smdgCode;
        this.terminalName = terminalName;
        this.terminalOperator = terminalOperator;
    }

    public Integer getId() {
        return this.id;
    }

    public Terminal setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getPort() {
        return this.port;
    }

    public Terminal setPort(Integer port) {
        this.port = port;
        return this;
    }

    public String getSmdgCode() {
        return this.smdgCode;
    }

    public Terminal setSmdgCode(String smdgCode) {
        this.smdgCode = smdgCode;
        return this;
    }

    public String getTerminalName() {
        return this.terminalName;
    }

    public Terminal setTerminalName(String terminalName) {
        this.terminalName = terminalName;
        return this;
    }

    public String getTerminalOperator() {
        return this.terminalOperator;
    }

    public Terminal setTerminalOperator(String terminalOperator) {
        this.terminalOperator = terminalOperator;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Terminal (");

        sb.append(id);
        sb.append(", ").append(port);
        sb.append(", ").append(smdgCode);
        sb.append(", ").append(terminalName);
        sb.append(", ").append(terminalOperator);

        sb.append(")");
        return sb.toString();
    }
}
