/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vessel implements Serializable {

    private static final long serialVersionUID = 1707730660;

    private Integer id;
    private String  name;
    private Integer imo;
    private Short   teu;
    private String  serviceName;

    public Vessel() {}

    public Vessel(Vessel value) {
        this.id = value.id;
        this.name = value.name;
        this.imo = value.imo;
        this.teu = value.teu;
        this.serviceName = value.serviceName;
    }

    public Vessel(
        Integer id,
        String  name,
        Integer imo,
        Short   teu,
        String  serviceName
    ) {
        this.id = id;
        this.name = name;
        this.imo = imo;
        this.teu = teu;
        this.serviceName = serviceName;
    }

    public Integer getId() {
        return this.id;
    }

    public Vessel setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Vessel setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getImo() {
        return this.imo;
    }

    public Vessel setImo(Integer imo) {
        this.imo = imo;
        return this;
    }

    public Short getTeu() {
        return this.teu;
    }

    public Vessel setTeu(Short teu) {
        this.teu = teu;
        return this;
    }

    public String getServiceName() {
        return this.serviceName;
    }

    public Vessel setServiceName(String serviceName) {
        this.serviceName = serviceName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vessel (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(imo);
        sb.append(", ").append(teu);
        sb.append(", ").append(serviceName);

        sb.append(")");
        return sb.toString();
    }
}
