/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vessel implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Integer imo;
    private Short   teu;
    private String  serviceNameCode;

    public Vessel() {}

    public Vessel(Vessel value) {
        this.id = value.id;
        this.name = value.name;
        this.imo = value.imo;
        this.teu = value.teu;
        this.serviceNameCode = value.serviceNameCode;
    }

    public Vessel(
        Integer id,
        String  name,
        Integer imo,
        Short   teu,
        String  serviceNameCode
    ) {
        this.id = id;
        this.name = name;
        this.imo = imo;
        this.teu = teu;
        this.serviceNameCode = serviceNameCode;
    }

    /**
     * Getter for <code>public.vessel.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.vessel.id</code>.
     */
    public Vessel setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.vessel.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.vessel.name</code>.
     */
    public Vessel setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.vessel.imo</code>.
     */
    public Integer getImo() {
        return this.imo;
    }

    /**
     * Setter for <code>public.vessel.imo</code>.
     */
    public Vessel setImo(Integer imo) {
        this.imo = imo;
        return this;
    }

    /**
     * Getter for <code>public.vessel.teu</code>.
     */
    public Short getTeu() {
        return this.teu;
    }

    /**
     * Setter for <code>public.vessel.teu</code>.
     */
    public Vessel setTeu(Short teu) {
        this.teu = teu;
        return this;
    }

    /**
     * Getter for <code>public.vessel.service_name_code</code>.
     */
    public String getServiceNameCode() {
        return this.serviceNameCode;
    }

    /**
     * Setter for <code>public.vessel.service_name_code</code>.
     */
    public Vessel setServiceNameCode(String serviceNameCode) {
        this.serviceNameCode = serviceNameCode;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vessel (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(imo);
        sb.append(", ").append(teu);
        sb.append(", ").append(serviceNameCode);

        sb.append(")");
        return sb.toString();
    }
}
