export enum PortCallServiceTypeCode {
  PILO = "PILO",
  MOOR = "MOOR",
  CRGO = "CRGO",
  TOWG = "TOWG",
  BUNK = "BUNK",
  LASH = "LASH",
  SAFE = "SAFE",
  FAST = "FAST",
  GWAY = "GWAY",
  ANCO = "ANCO",
  SLUG = "SLUG",
  SHPW = "SHPW",
  LCRO = "LCRO",
  DCRO = "DCRO",
  VRDY = "VRDY",
}
