/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.enums;


import org.dcsa.portcall.db.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum DelayType implements EnumType {

    SHIP_Related("SHIP Related"),

    SHORE_Related("SHORE Related"),

    CARGO_Related("CARGO Related"),

    Force_Majeure("Force Majeure"),

    Planned_Events("Planned Events");

    private final String literal;

    private DelayType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "delay_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
