/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.enums;


import org.dcsa.portcall.db.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum MessageDirection implements EnumType {

    inbound("inbound"),

    outbound("outbound");

    private final String literal;

    private MessageDirection(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "message_direction";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
