/*
 * This file is generated by jOOQ.
 */
package org.dcsa.portcall.db.enums;


import org.dcsa.portcall.db.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PortCallTimestampType implements EnumType {

    ETA_Berth("ETA-Berth"),

    RTA_Berth("RTA-Berth"),

    PTA_Berth("PTA-Berth"),

    ATA_Berth("ATA-Berth"),

    ETA_PBP("ETA-PBP"),

    RTA_PBP("RTA-PBP"),

    PTA_PBP("PTA-PBP"),

    ATA_PBP("ATA-PBP"),

    ATS("ATS"),

    ETC_Cargo_Ops("ETC Cargo Ops"),

    RTC_Cargo_Ops("RTC Cargo Ops"),

    PTC_Cargo_Ops("PTC Cargo Ops"),

    ATC_Cargo_Ops("ATC Cargo Ops"),

    ETD_Berth("ETD-Berth"),

    RTD_Berth("RTD-Berth"),

    PTD_Berth("PTD-Berth"),

    ATD_Berth("ATD-Berth");

    private final String literal;

    private PortCallTimestampType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "port_call_timestamp_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
