---
version: 2
plan:
  project-key: DCSA
  key: APP
  name: Build the PortCall application

branches:
  create:
    for-new-branch: (feature|release|hotfix)\/.*
  delete:
    after-inactive-days: 30
    after-deleted-days: 7

triggers:
  - polling: 300

stages:
  - Build Application:
      jobs:
        - Build

Build:
  tasks:
    - maven:
        executable: Maven 3.6
        jdk: OpenJDK 11
        goal: ponton.product.maven.plugins:createversion-maven-plugin:create versions:set
        tests: false
    - maven:
        executable: Maven 3.6
        jdk: OpenJDK 11
        goal: clean deploy
        tests: false
  final-tasks:
    - clean