---
version: 2
plan:
  project-key: DCSA
  key: APP
  name: Build the PortCall application

triggers:
  - polling: 300

stages:
  - Build Application:
      jobs:
        - Build

Build:
  tasks:
    - script:
        - ${bamboo_capability_system_builder_mvn3_maven_3_6}/bin/mvn clean deploy
  final-tasks:
    - clean