server:
  address: 127.0.0.1
  port: 8080

spring:
  application:
    name: portcall
  main:
    banner-mode: off
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/dcsa
    username: dcsa
    password: dcsapw
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 30000
      minimum-idle: 0
      maximum-pool-size: 10
      max-lifetime: 60000
      leak-detection-threshold: 30000
  flyway:
    url: jdbc:postgresql://127.0.0.1:5432/dcsa
    user: dcsa
    password: dcsapw

  jooq:
    sql-dialect: postgres

management:
  auditevents:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    auditevents:
      enabled: true
    beans:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    flyway:
      enabled: true
    health:
      enabled: true
    httptrace:
      enabled: true
    info:
      enabled: true
    integrationgraph:
      enabled: true
    logfile:
      enabled: true
      external-file: logs/dcsa.log
    loggers:
      enabled: true
    metrics:
      enabled: true
    mappings:
      enabled: true
    sessions:
      enabled: true

springdoc:
  show-actuator: true

dcsa:
  company: Development
  sender-role: CARRIER
  sender-id-type: SMDG_LINER_CODE
  sender-id: EXP

  hotfolder:
    outbox: "hotfolder/outbox"
    inbox: "hotfolder/inbox"

  messenger:
    adapter:
      id: DCSA
      version: 1.0
    host: localhost
    port: 2600
