name: Build P6 Application

on:
  push:
    branches:
      - master
      - main-dev
  pull_request:
    branches:
      - master
      - main-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure maven settings
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: '[{ "id": "dcsa-p6", "username": "${{ secrets.DCSA_USER }}", "password": "${{ secrets.DCSA_PACKAGES_PAT }}" }]'
      - name: Compile and test
        run: mvn -B package
#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v1
#        with:
#          report_paths: '**/surefire-reports/TEST-*.xml'
#          github_token: ${{ secrets.GITHUB_TOKEN }}
